// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtwKZh9T0iDEDSTaztFMoE6_KL4VYx7g',
    appId: '1:803131178140:web:be12acc3edc9aaa5a68159',
    messagingSenderId: '803131178140',
    projectId: 'quizzard-e1340',
    authDomain: 'quizzard-e1340.firebaseapp.com',
    storageBucket: 'quizzard-e1340.firebasestorage.app',
    measurementId: 'G-VK7WSSS5EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusIF5LGqA9MwUyXXc0D6koL6Wr5hnjUE',
    appId: '1:803131178140:android:a5ff464d401fdedca68159',
    messagingSenderId: '803131178140',
    projectId: 'quizzard-e1340',
    storageBucket: 'quizzard-e1340.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJohYWiQ8dbM3G1h2X4_ewpy9R-Uw8750',
    appId: '1:803131178140:ios:f7a5c9c3275a503aa68159',
    messagingSenderId: '803131178140',
    projectId: 'quizzard-e1340',
    storageBucket: 'quizzard-e1340.firebasestorage.app',
    iosBundleId: 'com.stabcorp.quizzard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJohYWiQ8dbM3G1h2X4_ewpy9R-Uw8750',
    appId: '1:803131178140:ios:f7a5c9c3275a503aa68159',
    messagingSenderId: '803131178140',
    projectId: 'quizzard-e1340',
    storageBucket: 'quizzard-e1340.firebasestorage.app',
    iosBundleId: 'com.stabcorp.quizzard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtwKZh9T0iDEDSTaztFMoE6_KL4VYx7g',
    appId: '1:803131178140:web:bbf72d51b1db6170a68159',
    messagingSenderId: '803131178140',
    projectId: 'quizzard-e1340',
    authDomain: 'quizzard-e1340.firebaseapp.com',
    storageBucket: 'quizzard-e1340.firebasestorage.app',
    measurementId: 'G-SDPK4ZQFYH',
  );
}