import 'package:flutter/material.dart';
import 'quiz_models.dart';
// --- SAMPLE DATA ---
final List<QuizCategory> quizCategories = [
  QuizCategory(
    name: "World Quiz",
    assetImagePath: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600",
    difficulty: Difficulty.easy,
  ),
  QuizCategory(
    name: "Bollywood",
    assetImagePath: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600",
    difficulty: Difficulty.easy,
  ),
  QuizCategory(
    name: "Geography",
    assetImagePath: "https://images.unsplash.com/photo-1502920514313-52581002a659?w=600",
    difficulty: Difficulty.easy,
  ),
  QuizCategory(
    name: "Science",
    assetImagePath: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600",
    difficulty: Difficulty.medium,
  ),
  QuizCategory(
    name: "History",
    assetImagePath: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600",
    difficulty: Difficulty.medium,
  ),
  QuizCategory(
    name: "India",
    assetImagePath: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600",
    difficulty: Difficulty.easy,
  ),
  QuizCategory(
    name: "Australia",
    assetImagePath: "https://images.unsplash.com/photo-1506973035872-a4f23e5764e4?w=600",
    difficulty: Difficulty.easy,
  ),
  QuizCategory(
    name: "USA",
    assetImagePath: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600",
    difficulty: Difficulty.medium,
  ),
  QuizCategory(
    name: "China",
    assetImagePath: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600",
    difficulty: Difficulty.medium,
  ),
  QuizCategory(
    name: "Flags",
    assetImagePath: "https://images.unsplash.com/photo-1502920917128-1aa500764b7a?w=600",
    difficulty: Difficulty.hard,
  ),
  QuizCategory(
    name: "Tech",
    assetImagePath: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600",
    difficulty: Difficulty.hard,
  ),
  QuizCategory(
    name: "Brands",
    assetImagePath: "https://images.unsplash.com/photo-1520607162513-77705c0f0d4a?w=600",
    difficulty: Difficulty.hard,
  ),
];

final Map<String, List<Question>> allQuestions = {
  "World Quiz": [
    Question(
      text: "Which country is home to the Eiffel Tower?",
      options: ["Italy", "France", "Spain", "Germany"],
      correctIndex: 1,
      trivia: "The Eiffel Tower was the world's tallest man-made structure for 41 years.",
      mediaUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the capital of Japan?",
      options: ["Beijing", "Seoul", "Tokyo", "Bangkok"],
      correctIndex: 2,
      trivia: "Tokyo is the most populous metropolitan area in the world.",
      mediaUrl: "https://images.unsplash.com/photo-1503899738202-7c852441d3d6?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the longest river in the world?",
      options: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"],
      correctIndex: 1,
      trivia: "The Nile River flows for approximately 6,650 kilometers (4,132 miles) through northeastern Africa.",
      mediaUrl: "https://images.unsplash.com/photo-1577935749419-866ad505a769?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which country is famous for the Great Wall?",
      options: ["India", "China", "Egypt", "Russia"],
      correctIndex: 1,
      trivia: "The Great Wall of China is a series of fortifications built across the historical northern borders of ancient Chinese states.",
      mediaUrl: "https://images.unsplash.com/photo-1522818049184-e9ed4b986f34?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the capital of Australia?",
      options: ["Sydney", "Melbourne", "Canberra", "Perth"],
      correctIndex: 2,
      trivia: "Many people mistakenly think Sydney or Melbourne is the capital, but it's Canberra.",
      mediaUrl: "https://images.unsplash.com/photo-1506973035049-aa674c5d9c22?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which city is known as the 'City of Love'?",
      options: ["Rome", "Venice", "Paris", "New York"],
      correctIndex: 2,
      trivia: "Paris, the capital of France, is often called the 'City of Love' due to its romantic ambiance.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "The ancient city of Petra is located in which country?",
      options: ["Egypt", "Jordan", "Greece", "Turkey"],
      correctIndex: 1,
      trivia: "Petra is a famous archaeological site in Jordan, known for its rock-cut architecture.",
      mediaUrl: "https://images.unsplash.com/photo-1555547464-ec3a0d9b4b61?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which country is the smallest in the world?",
      options: ["Monaco", "Nauru", "Vatican City", "San Marino"],
      correctIndex: 2,
      trivia: "Vatican City is an independent city-state located within Rome, Italy.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Mount Everest is located in which mountain range?",
      options: ["Andes", "Rockies", "Himalayas", "Alps"],
      correctIndex: 2,
      trivia: "Mount Everest is the Earth's highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas.",
      mediaUrl: "https://images.unsplash.com/photo-1589803159043-34e8d3b841c2?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The Taj Mahal is located in which Indian city?",
      options: ["Mumbai", "Delhi", "Agra", "Jaipur"],
      correctIndex: 2,
      trivia: "The Taj Mahal is an ivory-white marble mausoleum on the right bank of the river Yamuna in the Indian city of Agra.",
      mediaUrl: "https://images.unsplash.com/photo-1564507579177-c990059f7dfc?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
  ],
  "Bollywood": [
    Question(
      text: "Who is known as the 'King of Bollywood'?",
      options: ["Salman Khan", "Shah Rukh Khan", "Aamir Khan", "Akshay Kumar"],
      correctIndex: 1,
      trivia: "Shah Rukh Khan has starred in over 80 films and won numerous awards.",
      mediaUrl: "https://images.unsplash.com/photo-1564507579177-c990059f7dfc?w=500", // Placeholder, find a better one
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which movie famously features the song 'Chaiyya Chaiyya'?",
      options: ["Dil Se..", "Kal Ho Naa Ho", "Kuch Kuch Hota Hai", "Kabhi Khushi Kabhie Gham"],
      correctIndex: 0,
      trivia: "The song was shot on top of a moving train, which was a unique feat for its time.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Who directed the iconic film 'Lagaan'?",
      options: ["Karan Johar", "Aditya Chopra", "Ashutosh Gowariker", "Sanjay Leela Bhansali"],
      correctIndex: 2,
      trivia: "Lagaan was nominated for an Academy Award for Best Foreign Language Film.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which actress is often referred to as the 'Dream Girl' of Bollywood?",
      options: ["Madhuri Dixit", "Sridevi", "Hema Malini", "Rekha"],
      correctIndex: 2,
      trivia: "Hema Malini has starred in over 150 films and is also a trained Bharatanatyam dancer.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which film is considered India's first sound film?",
      options: ["Raja Harishchandra", "Alam Ara", "Kismet", "Mother India"],
      correctIndex: 1,
      trivia: "Alam Ara, released in 1931, marked the beginning of sound films in Indian cinema.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Who is known as the 'Shahenshah of Bollywood'?",
      options: ["Rajesh Khanna", "Dev Anand", "Amitabh Bachchan", "Dharmendra"],
      correctIndex: 2,
      trivia: "Amitabh Bachchan has had a prolific career spanning over five decades.",
      mediaUrl: "https://images.unsplash.com/photo-1564507579177-c990059f7dfc?w=500", // Placeholder, find a better one
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which Bollywood movie is based on the life of Indian boxer Mary Kom?",
      options: ["Dangal", "Bhaag Milkha Bhaag", "Mary Kom", "Sultan"],
      correctIndex: 2,
      trivia: "Priyanka Chopra played the lead role in the biographical film 'Mary Kom'.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which famous director is known for his elaborate sets and grand musical numbers?",
      options: ["Imtiaz Ali", "Anurag Kashyap", "Sanjay Leela Bhansali", "Zoya Akhtar"],
      correctIndex: 2,
      trivia: "Sanjay Leela Bhansali's films are known for their visual splendor and emotional depth.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which is the highest-grossing Indian film of all time (worldwide)?",
      options: ["Baahubali 2: The Conclusion", "Dangal", "Secret Superstar", "PK"],
      correctIndex: 1,
      trivia: "Dangal, starring Aamir Khan, is a biographical sports drama based on the Phogat family.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Who sung the famous Bollywood song 'Kabhi Kabhie Mere Dil Mein'?",
      options: ["Mohammed Rafi", "Kishore Kumar", "Mukesh", "Lata Mangeshkar"],
      correctIndex: 2,
      trivia: "Mukesh was a legendary playback singer, often referred to as 'The Voice of Romance'.",
      difficulty: Difficulty.medium,
    ),
  ],
  "Geography": [
    Question(
      text: "Which mountain range runs along the western side of South America?",
      options: ["Himalayas", "Andes", "Rockies", "Alps"],
      correctIndex: 1,
      trivia: "The Andes is the longest continental mountain range in the world.",
      mediaUrl: "https://images.unsplash.com/photo-1544485122-83b1a8d4d8c6?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the name of the strait that separates Europe from Africa?",
      options: ["Bosphorus Strait", "Strait of Hormuz", "Strait of Gibraltar", "Dover Strait"],
      correctIndex: 2,
      trivia: "The Strait of Gibraltar connects the Atlantic Ocean to the Mediterranean Sea.",
      mediaUrl: "https://images.unsplash.com/photo-1588665792900-5e3a3e3c3b01?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which country is known as the 'Land of the Rising Sun'?",
      options: ["China", "South Korea", "Japan", "Vietnam"],
      correctIndex: 2,
      trivia: "Japan's name in Japanese is 'Nihon' or 'Nippon', which literally means 'the sun's origin'.",
      mediaUrl: "https://images.unsplash.com/photo-1509930960098-b64802c610d4?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the capital of New Zealand?",
      options: ["Auckland", "Christchurch", "Wellington", "Queenstown"],
      correctIndex: 2,
      trivia: "Wellington is New Zealand's capital and the southernmost capital city in the world.",
      mediaUrl: "https://images.unsplash.com/photo-1510425712217-0b1a0e8c8b6d?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which desert is located in northern Africa?",
      options: ["Gobi Desert", "Kalahari Desert", "Sahara Desert", "Arabian Desert"],
      correctIndex: 2,
      trivia: "The Sahara is the largest hot desert in the world and the third-largest desert overall after the Antarctic and Arctic polar deserts.",
      mediaUrl: "https://images.unsplash.com/photo-1549419163-4a0b2b80a221?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which river flows through Paris, France?",
      options: ["Rhine", "Thames", "Seine", "Danube"],
      correctIndex: 2,
      trivia: "The Seine River is a major commercial waterway within the Paris Basin.",
      mediaUrl: "https://images.unsplash.com/photo-1502602898666-ae368d1f2e86?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the largest lake in Africa?",
      options: ["Lake Tanganyika", "Lake Malawi", "Lake Victoria", "Lake Chad"],
      correctIndex: 2,
      trivia: "Lake Victoria is the largest lake in Africa by area and the world's second-largest freshwater lake by surface area.",
      mediaUrl: "https://images.unsplash.com/photo-1589718446258-c70f0f3e2e71?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which country is both an island and a continent?",
      options: ["Madagascar", "Greenland", "Australia", "Iceland"],
      correctIndex: 2,
      trivia: "Australia is the only country that is also a continent.",
      mediaUrl: "https://images.unsplash.com/photo-1517457375-9c8a0050d24f?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the driest inhabited continent on Earth?",
      options: ["Africa", "Asia", "Australia", "South America"],
      correctIndex: 2,
      trivia: "Australia receives the least rainfall of any continent, making it the driest.",
      mediaUrl: "https://images.unsplash.com/photo-1522818049184-e9ed4b986f34?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which sea is located between Europe and Africa?",
      options: ["Black Sea", "Red Sea", "Mediterranean Sea", "Adriatic Sea"],
      correctIndex: 2,
      trivia: "The Mediterranean Sea is almost completely enclosed by land, bordered by Southern Europe, North Africa, and Western Asia.",
      mediaUrl: "https://images.unsplash.com/photo-1516246830501-8f9f7d4b4f5e?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
  ],
  "Science": [
    Question(
      text: "What is the chemical symbol for Oxygen?",
      options: ["O", "Ox", "O2", "H2O"],
      correctIndex: 0,
      trivia: "Oxygen is element 8 on the periodic table and essential for most life.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which planet is known as the Red Planet?",
      options: ["Earth", "Mars", "Jupiter", "Saturn"],
      correctIndex: 1,
      trivia: "Mars looks red due to iron oxide (rust) on its surface.",
      mediaUrl: "https://images.unsplash.com/photo-1614728266904-1428f5228514?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What force keeps planets in orbit around the Sun?",
      options: ["Magnetic force", "Centrifugal force", "Gravity", "Friction"],
      correctIndex: 2,
      trivia: "Gravity is the fundamental force that pulls masses toward each other.",
      mediaUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the process by which plants make their own food?",
      options: ["Respiration", "Fermentation", "Photosynthesis", "Transpiration"],
      correctIndex: 2,
      trivia: "Photosynthesis converts light energy into chemical energy.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the smallest unit of matter?",
      options: ["Molecule", "Atom", "Cell", "Proton"],
      correctIndex: 1,
      trivia: "Atoms are the basic building blocks of chemical elements.",
      mediaUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which gas do humans breathe out?",
      options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
      correctIndex: 2,
      trivia: "Carbon dioxide is a waste product of cellular respiration.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the hardest natural substance on Earth?",
      options: ["Gold", "Iron", "Diamond", "Quartz"],
      correctIndex: 2,
      trivia: "Diamond is a form of carbon with a rigid crystal lattice.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which instrument measures earthquakes?",
      options: ["Barometer", "Anemometer", "Seismograph", "Telescope"],
      correctIndex: 2,
      trivia: "Seismographs record ground motion during quakes.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which element is the basis of organic chemistry?",
      options: ["Oxygen", "Nitrogen", "Carbon", "Hydrogen"],
      correctIndex: 2,
      trivia: "Carbon forms stable bonds with many elements, creating complex molecules.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "What is the common name for Dihydrogen Monoxide?",
      options: ["Hydrogen Peroxide", "Ammonia", "Water", "Methane"],
      correctIndex: 2,
      trivia: "Dihydrogen Monoxide is just water (H2O).",
      difficulty: Difficulty.easy,
    ),
  ],
  "History": [
    Question(
      text: "Who was the first President of the United States?",
      options: ["Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams"],
      correctIndex: 2,
      trivia: "George Washington led the Continental Army during the American Revolution.",
      mediaUrl: "https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "In what year did World War II end?",
      options: ["1918", "1939", "1945", "1950"],
      correctIndex: 2,
      trivia: "The war ended in 1945 with the surrender of Japan.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which ancient civilization built the pyramids of Giza?",
      options: ["Roman", "Greek", "Egyptian", "Mayan"],
      correctIndex: 2,
      trivia: "The Great Pyramid is the oldest of the Seven Wonders.",
      mediaUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Who wrote the play 'Romeo and Juliet'?",
      options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Mark Twain"],
      correctIndex: 1,
      trivia: "Shakespeare wrote over 30 plays and 150 sonnets.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The fall of the Berlin Wall occurred in which year?",
      options: ["1979", "1985", "1989", "1991"],
      correctIndex: 2,
      trivia: "Its fall symbolized the end of the Cold War.",
      mediaUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Who was the queen of ancient Egypt who allied with Julius Caesar and Mark Antony?",
      options: ["Nefertiti", "Hatshepsut", "Cleopatra", "Ankhesenamun"],
      correctIndex: 2,
      trivia: "Cleopatra VII was the last active ruler of Ptolemaic Egypt.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "In which year did Christopher Columbus first arrive in the Americas?",
      options: ["1452", "1492", "1500", "1520"],
      correctIndex: 1,
      trivia: "Columbus reached the Americas in 1492.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The Magna Carta was signed in which country?",
      options: ["France", "England", "Germany", "Italy"],
      correctIndex: 1,
      trivia: "Signed in 1215, it limited the power of the English king.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Who was the leader of Nazi Germany during World War II?",
      options: ["Benito Mussolini", "Joseph Stalin", "Winston Churchill", "Adolf Hitler"],
      correctIndex: 3,
      trivia: "Hitler became Chancellor of Germany in 1933.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "The Industrial Revolution began in which country?",
      options: ["France", "Germany", "United States", "Great Britain"],
      correctIndex: 3,
      trivia: "It began in Great Britain in the late 18th century.",
      difficulty: Difficulty.medium,
    ),
  ],
  "India": [
    Question(
      text: "Which Indian city is known as the 'Pink City'?",
      options: ["Delhi", "Mumbai", "Jaipur", "Chennai"],
      correctIndex: 2,
      trivia: "Jaipur is famous for its distinct pink-colored buildings and historical palaces.",
      mediaUrl: "https://images.unsplash.com/photo-1582570075677-4c75e24b7a13?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "The festival of Diwali is primarily associated with which religion?",
      options: ["Islam", "Christianity", "Hinduism", "Buddhism"],
      correctIndex: 2,
      trivia: "Diwali is the festival of lights, symbolizing the victory of light over darkness and good over evil.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which Indian monument was built by Emperor Shah Jahan in memory of his wife Mumtaz Mahal?",
      options: ["Red Fort", "Qutub Minar", "Hawa Mahal", "Taj Mahal"],
      correctIndex: 3,
      trivia: "The Taj Mahal is a UNESCO World Heritage Site and one of the New7Wonders of the World.",
      mediaUrl: "https://images.unsplash.com/photo-1564507579177-c990059f7dfc?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Who is known as the 'Father of the Indian Nation'?",
      options: ["Jawaharlal Nehru", "Sardar Patel", "Mahatma Gandhi", "Subhas Chandra Bose"],
      correctIndex: 2,
      trivia: "Mahatma Gandhi led India to independence from British rule through nonviolent civil disobedience.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which river is considered the most sacred river in Hinduism?",
      options: ["Yamuna", "Godavari", "Ganges", "Brahmaputra"],
      correctIndex: 2,
      trivia: "The Ganges River (Ganga) is revered as a holy river by Hindus, who believe bathing in its waters can cleanse sins.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The Indian national animal is the:",
      options: ["Elephant", "Lion", "Tiger", "Peacock"],
      correctIndex: 2,
      trivia: "The Bengal tiger is a majestic animal, symbolizing India's wildlife heritage.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which ancient Indian text is a collection of hymns, prayers, and philosophical treatises?",
      options: ["Ramayana", "Mahabharata", "Vedas", "Upanishads"],
      correctIndex: 2,
      trivia: "The Vedas are among the oldest sacred texts of Hinduism.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which Indian state is known as the 'Land of Five Rivers'?",
      options: ["Rajasthan", "Uttar Pradesh", "Punjab", "Gujarat"],
      correctIndex: 2,
      trivia: "Punjab gets its name from five major rivers that flow through it: Beas, Chenab, Jhelum, Ravi, and Sutlej.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which of these Indian spices is often referred to as 'black gold'?",
      options: ["Cardamom", "Turmeric", "Cinnamon", "Black Pepper"],
      correctIndex: 3,
      trivia: "Black pepper was once a valuable commodity, used as a currency and a luxury spice.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "The Indian classical dance form 'Kathak' originated from which region?",
      options: ["South India", "East India", "North India", "West India"],
      correctIndex: 2,
      trivia: "Kathak is characterized by intricate footwork, graceful movements, and expressive storytelling.",
      difficulty: Difficulty.hard,
    ),
  ],
  "Australia": [
    Question(
      text: "Which iconic landmark is located in Sydney, Australia?",
      options: ["Big Ben", "Eiffel Tower", "Sydney Opera House", "Statue of Liberty"],
      correctIndex: 2,
      trivia: "The Sydney Opera House is a multi-venue performing arts centre and a UNESCO World Heritage Site.",
      mediaUrl: "https://images.unsplash.com/photo-1514757046112-9c97b878b27c?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which unique marsupial is native to Australia and known for its diet of eucalyptus leaves?",
      options: ["Kangaroo", "Wallaby", "Koala", "Wombat"],
      correctIndex: 2,
      trivia: "Koalas have a specialized digestive system to handle the toxic compounds in eucalyptus leaves.",
      mediaUrl: "https://images.unsplash.com/photo-1507747805211-7360098f4803?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the capital city of Australia?",
      options: ["Sydney", "Melbourne", "Canberra", "Perth"],
      correctIndex: 2,
      trivia: "Many people mistakenly think Sydney or Melbourne is the capital, but it's Canberra.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The Great Barrier Reef, the world's largest coral reef system, is located off the coast of which Australian state?",
      options: ["New South Wales", "Victoria", "Queensland", "Western Australia"],
      correctIndex: 2,
      trivia: "Queensland is a northeastern Australian state with a coastline stretching from tropical beaches to the coral of the Great Barrier Reef.",
      mediaUrl: "https://images.unsplash.com/photo-1593021430939-95a287e07a27?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which flightless bird is native to Australia and is the second-largest living bird by height?",
      options: ["Ostrich", "Cassowary", "Emu", "Kiwi"],
      correctIndex: 2,
      trivia: "Emus are soft-feathered, brown, flightless birds with long necks and legs, and can run at high speeds.",
      mediaUrl: "https://images.unsplash.com/photo-1610427976192-d6105f2c52e8?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the famous rock formation in the Northern Territory of Australia, also known as Uluru?",
      options: ["The Olgas", "Kata Tjuta", "Mount Augustus", "Ayers Rock"],
      correctIndex: 3,
      trivia: "Ayers Rock (Uluru) is a large sandstone rock formation in the southern part of the Northern Territory in central Australia.",
      mediaUrl: "https://images.unsplash.com/photo-1577789454848-038b1d9150f8?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which Australian animal is known for its ability to play dead when threatened?",
      options: ["Dingo", "Tasmanian Devil", "Kookaburra", "Possum"],
      correctIndex: 3,
      trivia: "Possums are known to 'play dead' (thanatosis) when threatened.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "The annual 'Melbourne Cup' is a famous race for which animal?",
      options: ["Dogs", "Horses", "Camels", "Pigeons"],
      correctIndex: 1,
      trivia: "The Melbourne Cup is Australia's most famous annual Thoroughbred horse race, run on the first Tuesday of November.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which Australian state is home to the city of Perth?",
      options: ["South Australia", "Western Australia", "Victoria", "Queensland"],
      correctIndex: 1,
      trivia: "Perth is the capital and largest city of Western Australia, located on the Swan River.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the traditional Aboriginal musical instrument, often made from a hollowed-out log?",
      options: ["Boomerang", "Didgeridoo", "Woomera", "Clapsticks"],
      correctIndex: 1,
      trivia: "The didgeridoo is a wind instrument developed by Indigenous Australians of northern Australia.",
      mediaUrl: "https://images.unsplash.com/photo-1546736412-16a72e82110c?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
  ],
  "USA": [
    Question(
      text: "Which monument is a symbol of freedom and democracy in New York City?",
      options: ["Golden Gate Bridge", "Washington Monument", "Statue of Liberty", "Mount Rushmore"],
      correctIndex: 2,
      trivia: "The Statue of Liberty was a gift from the people of France to the United States.",
      mediaUrl: "https://images.unsplash.com/photo-1549605342-9a3d4f4b1f4c?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the capital city of the United States?",
      options: ["New York City", "Los Angeles", "Washington, D.C.", "Chicago"],
      correctIndex: 2,
      trivia: "Washington, D.C., is not part of any state, but a federal district.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which famous landmark is a large national park primarily located in Wyoming, Montana, and Idaho?",
      options: ["Grand Canyon", "Yosemite National Park", "Yellowstone National Park", "Zion National Park"],
      correctIndex: 2,
      trivia: "Yellowstone is known for its geothermal features, including Old Faithful geyser.",
      mediaUrl: "https://images.unsplash.com/photo-1589803159043-34e8d3b841c2?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which U.S. state is known as the 'Sunshine State'?",
      options: ["California", "Florida", "Hawaii", "Arizona"],
      correctIndex: 1,
      trivia: "Florida is a popular tourist destination known for its beaches and theme parks.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "The American flag has how many stars?",
      options: ["13", "50", "52", "48"],
      correctIndex: 1,
      trivia: "Each star represents one of the 50 states of the United States of America.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which sport is often referred to as 'America's pastime'?",
      options: ["Basketball", "American Football", "Baseball", "Soccer"],
      correctIndex: 2,
      trivia: "Baseball has a long and rich history in the United States, with its origins tracing back to the 18th century.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which famous civil rights leader delivered the 'I Have a Dream' speech?",
      options: ["Malcolm X", "Martin Luther King Jr.", "Rosa Parks", "Frederick Douglass"],
      correctIndex: 1,
      trivia: "Martin Luther King Jr.'s speech is one of the most iconic and powerful speeches in American history.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the highest mountain peak in North America?",
      options: ["Mount Whitney", "Mount Rainier", "Denali (Mount McKinley)", "Mount Elbert"],
      correctIndex: 2,
      trivia: "Denali, located in Alaska, is the third most prominent peak after Mount Everest and Aconcagua.",
      mediaUrl: "https://images.unsplash.com/photo-1574345229300-8b1b2a9e5b61?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which U.S. city is famous for its cable cars and Alcatraz Island?",
      options: ["Seattle", "San Francisco", "Boston", "New Orleans"],
      correctIndex: 1,
      trivia: "San Francisco is a hilly city on the tip of a peninsula in northern California.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The Declaration of Independence was primarily written by whom?",
      options: ["George Washington", "Benjamin Franklin", "Thomas Jefferson", "John Adams"],
      correctIndex: 2,
      trivia: "Thomas Jefferson was the principal author of the Declaration of Independence.",
      difficulty: Difficulty.hard,
    ),
  ],
  "China": [
    Question(
      text: "Which famous wall is a series of fortifications built across the historical northern borders of ancient Chinese states?",
      options: ["Hadrian's Wall", "The Great Wall of China", "Berlin Wall", "Antonine Wall"],
      correctIndex: 1,
      trivia: "The Great Wall of China is one of the most iconic symbols of China.",
      mediaUrl: "https://images.unsplash.com/photo-1502691763135-c3359d9c8e19?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the capital city of China?",
      options: ["Shanghai", "Hong Kong", "Beijing", "Guangzhou"],
      correctIndex: 2,
      trivia: "Beijing is a massive city, known for its ancient history and modern development.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which animal, native to China, is known for its black and white fur and bamboo diet?",
      options: ["Red Panda", "Snow Leopard", "Giant Panda", "Siberian Tiger"],
      correctIndex: 2,
      trivia: "Giant Pandas are a symbol of conservation and are native to south central China.",
      mediaUrl: "https://images.unsplash.com/photo-1547432095-d22731804826?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which major river flows through Shanghai and is a significant waterway in China?",
      options: ["Yellow River", "Pearl River", "Yangtze River", "Xi River"],
      correctIndex: 2,
      trivia: "The Yangtze River is the longest river in Asia and the third-longest in the world.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the name of the ancient trade route that connected China with the West?",
      options: ["Spice Route", "Amber Road", "Silk Road", "Tea Horse Road"],
      correctIndex: 2,
      trivia: "The Silk Road was a network of trade routes connecting the East and West, crucial for cultural exchange.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which Chinese philosophy emphasizes harmony, filial piety, and respect for authority?",
      options: ["Taoism", "Legalism", "Confucianism", "Buddhism"],
      correctIndex: 2,
      trivia: "Confucianism has deeply influenced Chinese culture, politics, and education for centuries.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "The Terracotta Army is a collection of terracotta sculptures depicting the armies of which Chinese emperor?",
      options: ["Emperor Wu of Han", "Qin Shi Huang", "Emperor Taizong of Tang", "Kublai Khan"],
      correctIndex: 1,
      trivia: "The Terracotta Army was built to protect the emperor in his afterlife.",
      mediaUrl: "https://images.unsplash.com/photo-1588661706689-5f212f71f1e7?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which Chinese city is known for its iconic skyline, including the Oriental Pearl TV Tower?",
      options: ["Guangzhou", "Shenzhen", "Chongqing", "Shanghai"],
      correctIndex: 3,
      trivia: "Shanghai is a global financial hub and the most populous city in China.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the traditional Chinese art of folding paper into decorative shapes?",
      options: ["Calligraphy", "Peking Opera", "Origami", "Tai Chi"],
      correctIndex: 2,
      trivia: "While 'Origami' is commonly associated with Japan, paper folding also has a rich history in China.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which Chinese invention is used for navigation and was crucial for exploration?",
      options: ["Gunpowder", "Paper Making", "Printing", "Compass"],
      correctIndex: 3,
      trivia: "The compass was one of the Four Great Inventions of ancient China.",
      difficulty: Difficulty.hard,
    ),
  ],
  "Flags": [
    Question(
      text: "Which country's flag features a red circle on a white background?",
      options: ["South Korea", "China", "Japan", "Canada"],
      correctIndex: 2,
      trivia: "Japan's flag is called the Hinomaru, meaning 'circle of the sun'.",
      mediaUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "The maple leaf appears on the flag of which country?",
      options: ["United States", "Australia", "Canada", "New Zealand"],
      correctIndex: 2,
      trivia: "The maple leaf has been a Canadian symbol since the 18th century.",
      mediaUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which country's flag has a star and crescent?",
      options: ["Egypt", "Turkey", "Pakistan", "Algeria"],
      correctIndex: 1,
      trivia: "The star and crescent became associated with the Ottoman Empire.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which flag features a large yellow sun on a blue and white background?",
      options: ["Argentina", "Uruguay", "Brazil", "Chile"],
      correctIndex: 0,
      trivia: "Argentina's flag includes the Sun of May.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "The Union Jack is the national flag of which country?",
      options: ["United States", "Australia", "United Kingdom", "Canada"],
      correctIndex: 2,
      trivia: "It combines the crosses of England, Scotland, and Ireland.",
      mediaUrl: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which country's flag is the only non-rectangular national flag?",
      options: ["Nepal", "Bhutan", "Switzerland", "Vatican City"],
      correctIndex: 0,
      trivia: "Nepal's flag is made of two stacked pennants.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which flag has red and white stripes with a blue canton and 50 stars?",
      options: ["United States", "Liberia", "Malaysia", "Puerto Rico"],
      correctIndex: 0,
      trivia: "Each star represents a U.S. state.",
      mediaUrl: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which country's flag features a large cross on a white and red background?",
      options: ["Sweden", "Switzerland", "Denmark", "Norway"],
      correctIndex: 1,
      trivia: "Switzerland's flag is a square with a white cross.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which flag is green, white, and orange with a navy blue wheel?",
      options: ["Ireland", "India", "Italy", "Niger"],
      correctIndex: 1,
      trivia: "The navy blue wheel is the Ashoka Chakra.",
      mediaUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which flag has a red field with a large yellow star?",
      options: ["China", "Vietnam", "North Korea", "Cuba"],
      correctIndex: 1,
      trivia: "Vietnam's flag has a single five-pointed star.",
      difficulty: Difficulty.hard,
    ),
  ],
  "Tech": [
    Question(
      text: "Who co-founded Microsoft with Bill Gates?",
      options: ["Steve Jobs", "Paul Allen", "Mark Zuckerberg", "Larry Page"],
      correctIndex: 1,
      trivia: "Paul Allen helped write the original interpreter for Altair BASIC.",
      mediaUrl: "https://images.unsplash.com/photo-1518770660439-d3527e7f9191?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What does HTTP stand for?",
      options: ["HyperText Transfer Protocol", "High-Tech Transfer Program", "HyperTextured Text Protocol", "Home Tool Transfer Protocol"],
      correctIndex: 0,
      trivia: "HTTP is the foundation of data communication for the web.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which company developed the Android operating system?",
      options: ["Apple", "Microsoft", "Google", "Samsung"],
      correctIndex: 2,
      trivia: "Google acquired Android Inc. in 2005.",
      mediaUrl: "https://images.unsplash.com/photo-1518770660439-d3527e7f9191?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What is the name of Apple's virtual assistant?",
      options: ["Alexa", "Cortana", "Siri", "Google Assistant"],
      correctIndex: 2,
      trivia: "Siri debuted on the iPhone 4S in 2011.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which language is commonly used for AI and machine learning?",
      options: ["Java", "C++", "Python", "JavaScript"],
      correctIndex: 2,
      trivia: "Python has rich libraries like NumPy and TensorFlow.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "How many bits are in an IPv4 address?",
      options: ["16", "32", "64", "128"],
      correctIndex: 1,
      trivia: "IPv4 uses 32-bit addresses, shown as four octets.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which platform was originally called 'Thefacebook'?",
      options: ["Twitter", "Instagram", "Facebook", "LinkedIn"],
      correctIndex: 2,
      trivia: "It launched in 2004 for Harvard students.",
      mediaUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "What is the name of the first cryptocurrency?",
      options: ["Ethereum", "Litecoin", "Bitcoin", "Ripple"],
      correctIndex: 2,
      trivia: "Bitcoin was introduced in 2009 by Satoshi Nakamoto.",
      mediaUrl: "https://images.unsplash.com/photo-1518770660439-d3527e7f9191?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which company created the Windows operating system?",
      options: ["Apple", "IBM", "Microsoft", "Google"],
      correctIndex: 2,
      trivia: "Windows 1.0 was released in 1985.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "What does RAM stand for?",
      options: ["Random Access Memory", "Read-Only Memory", "Rapid Application Module", "Remote Access Mechanism"],
      correctIndex: 0,
      trivia: "RAM is temporary storage used by running programs.",
      difficulty: Difficulty.medium,
    ),
  ],
  "Brands": [
    Question(
      text: "Which car brand has a logo with a prancing horse?",
      options: ["Lamborghini", "Porsche", "Ferrari", "BMW"],
      correctIndex: 2,
      trivia: "The prancing horse was inspired by a WWI pilot's emblem.",
      mediaUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which fast-food chain is famous for the Big Mac?",
      options: ["Burger King", "Wendys", "McDonalds", "KFC"],
      correctIndex: 2,
      trivia: "The Big Mac was introduced in 1967.",
      mediaUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500",
      mediaType: MediaType.image,
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which brand uses the slogan 'Just Do It'?",
      options: ["Adidas", "Nike", "Puma", "Under Armour"],
      correctIndex: 1,
      trivia: "The slogan was introduced by Nike in 1988.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which company uses a bitten apple as its logo?",
      options: ["Microsoft", "Samsung", "Apple", "Google"],
      correctIndex: 2,
      trivia: "The logo is one of the most recognized in the world.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which coffee chain has a green mermaid logo?",
      options: ["Costa Coffee", "Starbucks", "Dunkin", "Tim Hortons"],
      correctIndex: 1,
      trivia: "The logo is a twin-tailed siren.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which luxury brand is known for interlocking CCs?",
      options: ["Gucci", "Louis Vuitton", "Chanel", "Hermes"],
      correctIndex: 2,
      trivia: "The logo was introduced in 1925.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which search engine is named after a 'googol'?",
      options: ["Bing", "Yahoo", "Google", "DuckDuckGo"],
      correctIndex: 2,
      trivia: "A googol is 1 followed by 100 zeros.",
      difficulty: Difficulty.medium,
    ),
    Question(
      text: "Which soft drink brand uses a red and white logo?",
      options: ["Pepsi", "Coca-Cola", "Sprite", "Fanta"],
      correctIndex: 1,
      trivia: "Coca-Cola has used its script logo since the 1880s.",
      difficulty: Difficulty.easy,
    ),
    Question(
      text: "Which car company makes the 911 sports car?",
      options: ["Ferrari", "Lamborghini", "Porsche", "Mercedes-Benz"],
      correctIndex: 2,
      trivia: "The 911 has been produced since 1963.",
      difficulty: Difficulty.hard,
    ),
    Question(
      text: "Which athletic brand is known for its three stripes?",
      options: ["Nike", "Puma", "Reebok", "Adidas"],
      correctIndex: 3,
      trivia: "The three stripes were added to Adidas products in 1949.",
      difficulty: Difficulty.easy,
    ),
  ],
};