// AUTO-GENERATED by scripts/buildPersonalities.js — do not edit by hand.
// Wikipedia portrait photos. Counts: {"Bollywood":30,"Hollywood":29,"Sports":30}

const personalityEntities = [
  {
    "category": "Bollywood",
    "name": "Amitabh Bachchan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Indian_actor_Amitabh_Bachchan.jpg/500px-Indian_actor_Amitabh_Bachchan.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Shah Rukh Khan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6e/Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Aamir Khan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/6/65/Aamir_Khan_at_the_success_bash_of_Secret_Superstar.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Salman Khan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Salman_Khan_in_2023_%281%29_%28cropped%29.jpg/500px-Salman_Khan_in_2023_%281%29_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Deepika Padukone",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Deepika_Padukone_2025_%281%29.png/500px-Deepika_Padukone_2025_%281%29.png"
  },
  {
    "category": "Bollywood",
    "name": "Priyanka Chopra",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/4/45/Priyanka_Chopra_at_Bulgary_launch%2C_2024_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Aishwarya Rai",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Aishwarya_Rai_Cannes_2017.jpg/500px-Aishwarya_Rai_Cannes_2017.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Ranbir Kapoor",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Ranbir_Kapoor_snapped_at_Kalina_airport.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Ranveer Singh",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/3/32/Ranveer_Singh_in_2023_%281%29_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Alia Bhatt",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Alia_Bhatt_attends_at_the_2026_Cannes_Film_Festival_%28cropped%29_%28cropped%29.jpg/500px-Alia_Bhatt_attends_at_the_2026_Cannes_Film_Festival_%28cropped%29_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Hrithik Roshan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/9/92/Hrithik_Roshan_in_2024_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Akshay Kumar",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Akshay_Kumar_National_Award_for_Padman_%28cropped%29.jpg/500px-Akshay_Kumar_National_Award_for_Padman_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Kareena Kapoor",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/29/Kareena_Kapoor_Khan_in_2023_%281%29_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Katrina Kaif",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Katrina_Kaif_at_the_Bharat_audio_launch.jpg/500px-Katrina_Kaif_at_the_Bharat_audio_launch.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Madhuri Dixit",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Madhuri_Dixit_in_November_2022.jpg/500px-Madhuri_Dixit_in_November_2022.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Anil Kapoor",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/0/08/Anil_Kapoor_1.jpeg"
  },
  {
    "category": "Bollywood",
    "name": "Ajay Devgn",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Ajay_Devgn_at_the_trailer_launch_of_Raid_2.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Vidya Balan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Vidya_Balan_at_BB3_interviews%2C_2024_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Kangana Ranaut",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f4/Kangana_Ranaut_at_Ira_Khan%27s_wedding_reception_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Nawazuddin Siddiqui",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Nawazuddin_Siddiqui_at_IFFK_2021_4_%28cropped%29.jpg/500px-Nawazuddin_Siddiqui_at_IFFK_2021_4_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Irrfan Khan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Irrfan_Khan_Profile.jpg/500px-Irrfan_Khan_Profile.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Rani Mukerji",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Rani_Mukerji_snapped_at_Hema_Malini%E2%80%99s_75th_birthday_celebration_%28cropped%29%282%29.jpg/500px-Rani_Mukerji_snapped_at_Hema_Malini%E2%80%99s_75th_birthday_celebration_%28cropped%29%282%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Saif Ali Khan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8b/Saif_SG_screening.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Vicky Kaushal",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/1/14/Vicky_Kaushal_snapped_promoting_Zara_Hatke_Zara_Bach_Ke_on_the_sets_of_The_Kapil_Sharma_Show_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Rajkummar Rao",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Actor_Rajkummar_Rao.jpg/500px-Actor_Rajkummar_Rao.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Kajol",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/4/41/Kajol_snapped_promoting_Maa_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Varun Dhawan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Varun_Dhawan_at_Mehboob_Studios_in_2025_%28cropped%29.jpg/500px-Varun_Dhawan_at_Mehboob_Studios_in_2025_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Shahid Kapoor",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Shahid_Kapoor_at_Bloody_Daddy_launch_%28cropped%29.jpg/500px-Shahid_Kapoor_at_Bloody_Daddy_launch_%28cropped%29.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Anushka Sharma",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e6/Anushka_Sharma_promoting_Zero.jpg"
  },
  {
    "category": "Bollywood",
    "name": "Ayushmann Khurrana",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e4/Ayushmann_Khurrana_promotos_%27Anek%27_in_Delhi_%281%29_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Leonardo DiCaprio",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/LeoPTABFI191125-28_%28cropped%29.jpg/500px-LeoPTABFI191125-28_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Brad Pitt",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Brad_Pitt-69858.jpg/500px-Brad_Pitt-69858.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Tom Cruise",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg/500px-Tom_Cruise_at_53rd_Saturn_Awards_2026-01.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Tom Hanks",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/TomHanksPrincEdw031223_%2811_of_41%29_%28cropped%29.jpg/500px-TomHanksPrincEdw031223_%2811_of_41%29_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Robert Downey Jr.",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/RobertDowneyJr-byPhilipRomano7_%28cropped%29.jpg/500px-RobertDowneyJr-byPhilipRomano7_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Scarlett Johansson",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Scarlett_Johansson-8588.jpg/500px-Scarlett_Johansson-8588.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Meryl Streep",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Meryl_Streep-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194765350_%28cropped1%29.jpg/500px-Meryl_Streep-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194765350_%28cropped1%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Denzel Washington",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Denzel_Washington_at_the_2025_Cannes_Film_Festival.jpg/500px-Denzel_Washington_at_the_2025_Cannes_Film_Festival.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Will Smith",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/TechCrunch_Disrupt_San_Francisco_2019_-_Day_1_%2848834070763%29_%28cropped%29.jpg/500px-TechCrunch_Disrupt_San_Francisco_2019_-_Day_1_%2848834070763%29_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Johnny Depp",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/21/Johnny_Depp_2020.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Angelina Jolie",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Angelina_Jolie-643531_%28cropped%29.jpg/500px-Angelina_Jolie-643531_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Jennifer Lawrence",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Jennifer_Lawrence_in_2018.png/500px-Jennifer_Lawrence_in_2018.png"
  },
  {
    "category": "Hollywood",
    "name": "Morgan Freeman",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_%28cropped%29.jpg/500px-Morgan_Freeman_at_The_Pentagon_on_2_August_2023_-_230802-D-PM193-3363_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Christian Bale",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Christian_Bale-7837.jpg/500px-Christian_Bale-7837.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Matt Damon",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/MattDamon-byPhilipRomano.jpg/500px-MattDamon-byPhilipRomano.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Natalie Portman",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/NataliePortman.jpg/500px-NataliePortman.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Anne Hathaway",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Anne_Hathaway-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194764955_%28cropped%29.jpg/500px-Anne_Hathaway-_Press_conference_for_the_film_%22The_Devil_Wears_Prada_2%22_-_55194764955_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Hugh Jackman",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Hugh_Jackman_by_Gage_Skidmore_3.jpg/500px-Hugh_Jackman_by_Gage_Skidmore_3.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Chris Hemsworth",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Chris_Hemsworth_-_Crime_101.jpg/500px-Chris_Hemsworth_-_Crime_101.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Keanu Reeves",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg/500px-Keanu_Reeves_at_TIFF_2025_02_%28Cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Samuel L. Jackson",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/SamuelLJackson.jpg/500px-SamuelLJackson.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Emma Stone",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Emma_Stone_at_the_2025_Venice_Film_Festival-6313_%28cropped%29.jpg/500px-Emma_Stone_at_the_2025_Venice_Film_Festival-6313_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Ryan Reynolds",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg/500px-Deadpool_2_Japan_Premiere_Red_Carpet_Ryan_Reynolds_%28cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Margot Robbie",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Margot_Robbie_at_29th_Critics%27_Choice_Awards.jpg_%28brightened%29.png/500px-Margot_Robbie_at_29th_Critics%27_Choice_Awards.jpg_%28brightened%29.png"
  },
  {
    "category": "Hollywood",
    "name": "Al Pacino",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Al_Pacino_2016_%2830401544240%29.jpg/500px-Al_Pacino_2016_%2830401544240%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Robert De Niro",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Robert_de_Niro_Cannes_Film_Festival_%283x4_cropped%29.jpg/500px-Robert_de_Niro_Cannes_Film_Festival_%283x4_cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Steven Spielberg",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/MKr25402_Steven_Spielberg_%28Berlinale_2023%29_%283x4_cropped%29.jpg/500px-MKr25402_Steven_Spielberg_%28Berlinale_2023%29_%283x4_cropped%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Christopher Nolan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/ChrisNolanBFI150224_%2810_of_12%29_%2853532289710%29_%28cropped2%29.jpg/500px-ChrisNolanBFI150224_%2810_of_12%29_%2853532289710%29_%28cropped2%29.jpg"
  },
  {
    "category": "Hollywood",
    "name": "Quentin Tarantino",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Quentin_Tarantino_by_Gage_Skidmore.jpg/500px-Quentin_Tarantino_by_Gage_Skidmore.jpg"
  },
  {
    "category": "Sports",
    "name": "Lionel Messi",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg/500px-Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Cristiano Ronaldo",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg/500px-President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Virat Kohli",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Virat_Kohli_in_PMO_New_Delhi.jpg/500px-Virat_Kohli_in_PMO_New_Delhi.jpg"
  },
  {
    "category": "Sports",
    "name": "Sachin Tendulkar",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/The_cricket_legend_Sachin_Tendulkar_at_the_Oval_Maidan_in_Mumbai_During_the_Duke_and_Duchess_of_Cambridge_Visit%2826271019082%29.jpg/500px-The_cricket_legend_Sachin_Tendulkar_at_the_Oval_Maidan_in_Mumbai_During_the_Duke_and_Duchess_of_Cambridge_Visit%2826271019082%29.jpg"
  },
  {
    "category": "Sports",
    "name": "MS Dhoni",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/MS_Dhoni_%28Prabhav_%2723_-_RiGI_2023%29.jpg/500px-MS_Dhoni_%28Prabhav_%2723_-_RiGI_2023%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Roger Federer",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Roger_Federer_2015_%28cropped%29.jpg/500px-Roger_Federer_2015_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Rafael Nadal",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Rafael_Nadal_en_2024_%28cropped%29.jpg/500px-Rafael_Nadal_en_2024_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Novak Djokovic",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Novak_Djokovic_Paris_2024_Olympic_Games_%28cropped%29.jpg/500px-Novak_Djokovic_Paris_2024_Olympic_Games_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Serena Williams",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2f/Guests_at_the_2026_Met_Gala_209_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Usain Bolt",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Usain_Bolt_smiling_Berlin_2009.JPG/500px-Usain_Bolt_smiling_Berlin_2009.JPG"
  },
  {
    "category": "Sports",
    "name": "LeBron James",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/LeBron_James_%2851959977144%29_%28cropped2%29.jpg/500px-LeBron_James_%2851959977144%29_%28cropped2%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Michael Jordan",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/a/ae/Michael_Jordan_in_2014.jpg"
  },
  {
    "category": "Sports",
    "name": "Tiger Woods",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/President_Donald_Trump_hosts_a_reception_honoring_Black_History_Month_%2854341713089%29_%28cropped%29.jpg/500px-President_Donald_Trump_hosts_a_reception_honoring_Black_History_Month_%2854341713089%29_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Lewis Hamilton",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg/500px-Prime_Minister_Keir_Starmer_meets_Sir_Lewis_Hamilton_%2854566928382%29_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Neymar",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Kylian Mbappé",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg/500px-Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Tom Brady",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg/500px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Tom_Brady_-_240422_191334_%28cropped%29_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Stephen Curry",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg/500px-Stephen_Curry%2C_Olympic_Games_2024_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Rohit Sharma",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg/500px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Shri_Rohit_Gurunath_Sharma_%28Cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Kobe Bryant",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Kobe_Bryant_Dec_2014.jpg/500px-Kobe_Bryant_Dec_2014.jpg"
  },
  {
    "category": "Sports",
    "name": "Diego Maradona",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/4/48/Argentina_celebrando_copa_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Pelé",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/5/5e/Pele_con_brasil_%28cropped%29.jpg"
  },
  {
    "category": "Sports",
    "name": "Muhammad Ali",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Muhammad_Ali_NYWTS.jpg/500px-Muhammad_Ali_NYWTS.jpg"
  },
  {
    "category": "Sports",
    "name": "Michael Phelps",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Michael_Phelps_Rio_Olympics_2016.jpg/500px-Michael_Phelps_Rio_Olympics_2016.jpg"
  },
  {
    "category": "Sports",
    "name": "P. V. Sindhu",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/NAC_Jewellers_Honors_Olympic_Silver_Medalist_PV_Sindhu.jpg/500px-NAC_Jewellers_Honors_Olympic_Silver_Medalist_PV_Sindhu.jpg"
  },
  {
    "category": "Sports",
    "name": "Sania Mirza",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/22/Sania_Mirza_in_Tennis_Premier_League_2021.jpg"
  },
  {
    "category": "Sports",
    "name": "Mike Tyson",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg/500px-Mike_Tyson_Photo_Op_GalaxyCon_Austin_2023.jpg"
  },
  {
    "category": "Sports",
    "name": "Ronaldinho",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ronaldinho_in_2019.jpg/500px-Ronaldinho_in_2019.jpg"
  },
  {
    "category": "Sports",
    "name": "Zinedine Zidane",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg"
  },
  {
    "category": "Sports",
    "name": "Saina Nehwal",
    "attributes": {},
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/7/70/Saina_Nehwal_in_2011.jpg"
  }
];

module.exports = { personalityEntities };
