// AUTO-GENERATED by scripts/buildMedia.js — do not edit by hand.
// anthems: 30, clips: 8

const anthemEntities = [
  {
    "category": "Anthems",
    "name": "India",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/9/94/Jana_Gana_Mana_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "United States",
    "attributes": {
      "continent": "Americas"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/6/65/Star_Spangled_Banner_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "France",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg"
  },
  {
    "category": "Anthems",
    "name": "Germany",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/4/45/Nationalhymne_der_Bundesrepublik_Deutschland.mp3"
  },
  {
    "category": "Anthems",
    "name": "Japan",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a3/Kimi_ga_Yo_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "Brazil",
    "attributes": {
      "continent": "Americas"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/8/84/Brazilian_Flag_Anthem_%28Ministry_of_Education%29.ogg"
  },
  {
    "category": "Anthems",
    "name": "Italy",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/4/47/Canto_degli_Italiani_-_Marina_Militare_%28strumentale%29.wav"
  },
  {
    "category": "Anthems",
    "name": "Spain",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c8/Marcha_Real-Royal_March_by_US_Navy_Band.ogg"
  },
  {
    "category": "Anthems",
    "name": "Russia",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/4/41/National_Anthem_of_Russia_%282000%29%2C_instrumental%2C_one_verse.ogg"
  },
  {
    "category": "Anthems",
    "name": "China",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b9/March_of_the_Volunteers_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "Canada",
    "attributes": {
      "continent": "Americas"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b3/Royal_anthem_Canada.ogg"
  },
  {
    "category": "Anthems",
    "name": "Australia",
    "attributes": {
      "continent": "Oceania"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a6/U.S._Navy_Band%2C_Advance_Australia_Fair_%28instrumental%29.ogg"
  },
  {
    "category": "Anthems",
    "name": "Mexico",
    "attributes": {
      "continent": "Americas"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9d/Himno_Nacional_Mexicano_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "Argentina",
    "attributes": {
      "continent": "Americas"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/c/cd/Himno_Nacional_Argentino_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "Egypt",
    "attributes": {
      "continent": "Africa"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f2/Bilady%2C_Bilady%2C_Bilady.ogg"
  },
  {
    "category": "Anthems",
    "name": "Turkey",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/9/99/Istikl%C3%A2l_Marsi_instrumetal.ogg"
  },
  {
    "category": "Anthems",
    "name": "Greece",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/d/db/Hymn_to_liberty_instrumental.oga"
  },
  {
    "category": "Anthems",
    "name": "Portugal",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/5/58/A_Portuguesa.ogg"
  },
  {
    "category": "Anthems",
    "name": "Netherlands",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f5/United_States_Navy_Band_-_Het_Wilhelmus_%28tempo_corrected%29.ogg"
  },
  {
    "category": "Anthems",
    "name": "Sweden",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/0/02/United_States_Navy_Band_-_Sweden.ogg"
  },
  {
    "category": "Anthems",
    "name": "Poland",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/b/b1/Mazurek_Dabrowskiego.ogg"
  },
  {
    "category": "Anthems",
    "name": "South Africa",
    "attributes": {
      "continent": "Africa"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1d/South_African_national_anthem.oga"
  },
  {
    "category": "Anthems",
    "name": "Kenya",
    "attributes": {
      "continent": "Africa"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/29/National_anthem_of_Kenya%2C_performed_by_the_United_States_Navy_Band.wav"
  },
  {
    "category": "Anthems",
    "name": "Nigeria",
    "attributes": {
      "continent": "Africa"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Nigeria%2C_We_Hail_Thee_-_Banda_do_Batalh%C3%A3o_da_Guarda_Presidencial%2C_2025.ogg"
  },
  {
    "category": "Anthems",
    "name": "Thailand",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f3/Thai_National_Anthem_-_US_Navy_Band.ogg"
  },
  {
    "category": "Anthems",
    "name": "Indonesia",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Indonesia_Raya_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "Pakistan",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/7/77/National_anthem_of_Pakistan%2C_instrumental.oga"
  },
  {
    "category": "Anthems",
    "name": "Bangladesh",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Amar_Sonar_Bangla_instrumental_by_US_Navy_Band.oga"
  },
  {
    "category": "Anthems",
    "name": "Israel",
    "attributes": {
      "continent": "Asia"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/26/Hatikvah_instrumental.ogg"
  },
  {
    "category": "Anthems",
    "name": "Norway",
    "attributes": {
      "continent": "Europe"
    },
    "mediaType": "audio",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/f/f6/Norway_%28National_Anthem%29.ogg"
  }
];

const clipEntities = [
  {
    "category": "Nature Clips",
    "name": "Elephant",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/a/a2/Elephants_Dream_%282006%29.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Lion",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c0/Tarzan_and_the_Golden_Lion_%281927%29.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Tiger",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/2/2b/Tiger_playing_with_a_piece_of_wood_in_a_pool.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Giraffe",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/9/91/Giraffe_in_Malawi_-_2018_Aug.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Penguin",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Penguin_at_Boulders_01.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Kangaroo",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/6/69/Boxing_Kangaroo_%281895%29.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Dolphin",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/7/78/In_situ_video_of_Santjordia_pagesi_holotype_specimen_HD84GS1_%28DLSI063%29_as_recorded_by_remotely_operated_underwater_vehicle_Hyper-Dolphin.webm"
  },
  {
    "category": "Nature Clips",
    "name": "Zebra",
    "attributes": {},
    "mediaType": "video",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/1/13/A_Zebra_at_the_Oribi_Gorge_Nature_reserve.webm"
  }
];

module.exports = { anthemEntities, clipEntities };
