// AUTO-GENERATED by scripts/buildSeedEntities.js — do not edit by hand.
// Source: REST Countries (UN members) + curated major-city lists.
// 192 countries, 33 with major-city pools.

const countryEntities = [
  {
    "category": "Countries",
    "name": "Afghanistan",
    "attributes": {
      "capital": "Kabul",
      "currency": "Afghan afghani",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 43844000
    },
    "mediaType": "image",
    "mediaUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png"
  },
  {
    "category": "Countries",
    "name": "Albania",
    "attributes": {
      "capital": "Tirana",
      "currency": "Albanian lek",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 2363314
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/al.png"
  },
  {
    "category": "Countries",
    "name": "Algeria",
    "attributes": {
      "capital": "Algiers",
      "currency": "Algerian dinar",
      "continent": "Africa",
      "subregion": "Northern Africa",
      "population": 47400000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/dz.png"
  },
  {
    "category": "Countries",
    "name": "Andorra",
    "attributes": {
      "capital": "Andorra la Vella",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 88406
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ad.png"
  },
  {
    "category": "Countries",
    "name": "Angola",
    "attributes": {
      "capital": "Luanda",
      "currency": "Angolan kwanza",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 36170961
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ao.png"
  },
  {
    "category": "Countries",
    "name": "Antigua and Barbuda",
    "attributes": {
      "capital": "Saint John's",
      "currency": "Eastern Caribbean dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 103603
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ag.png"
  },
  {
    "category": "Countries",
    "name": "Argentina",
    "attributes": {
      "capital": "Buenos Aires",
      "currency": "Argentine peso",
      "continent": "Americas",
      "subregion": "South America",
      "population": 46735004,
      "major_cities": [
        "Buenos Aires",
        "Córdoba",
        "Rosario",
        "Mendoza"
      ],
      "largest_city": "Buenos Aires"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ar.png"
  },
  {
    "category": "Countries",
    "name": "Armenia",
    "attributes": {
      "capital": "Yerevan",
      "currency": "Armenian dram",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 3076200
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/am.png"
  },
  {
    "category": "Countries",
    "name": "Australia",
    "attributes": {
      "capital": "Canberra",
      "currency": "Australian dollar",
      "continent": "Oceania",
      "subregion": "Australia and New Zealand",
      "population": 27536874,
      "major_cities": [
        "Sydney",
        "Melbourne",
        "Brisbane",
        "Perth",
        "Adelaide"
      ],
      "largest_city": "Sydney"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/au.png"
  },
  {
    "category": "Countries",
    "name": "Austria",
    "attributes": {
      "capital": "Vienna",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Central Europe",
      "population": 9200931
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/at.png"
  },
  {
    "category": "Countries",
    "name": "Azerbaijan",
    "attributes": {
      "capital": "Baku",
      "currency": "Azerbaijani manat",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 10241722
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/az.png"
  },
  {
    "category": "Countries",
    "name": "Bahamas",
    "attributes": {
      "capital": "Nassau",
      "currency": "Bahamian dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 398165
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bs.png"
  },
  {
    "category": "Countries",
    "name": "Bahrain",
    "attributes": {
      "capital": "Manama",
      "currency": "Bahraini dinar",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 1594654
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bh.png"
  },
  {
    "category": "Countries",
    "name": "Bangladesh",
    "attributes": {
      "capital": "Dhaka",
      "currency": "Bangladeshi taka",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 169828911,
      "major_cities": [
        "Dhaka",
        "Chittagong",
        "Khulna",
        "Rajshahi"
      ],
      "largest_city": "Dhaka"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bd.png"
  },
  {
    "category": "Countries",
    "name": "Barbados",
    "attributes": {
      "capital": "Bridgetown",
      "currency": "Barbadian dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 267800
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bb.png"
  },
  {
    "category": "Countries",
    "name": "Belarus",
    "attributes": {
      "capital": "Minsk",
      "currency": "Belarusian ruble",
      "continent": "Europe",
      "subregion": "Eastern Europe",
      "population": 9109280
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/by.png"
  },
  {
    "category": "Countries",
    "name": "Belgium",
    "attributes": {
      "capital": "Brussels",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 11825551
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/be.png"
  },
  {
    "category": "Countries",
    "name": "Belize",
    "attributes": {
      "capital": "Belmopan",
      "currency": "Belize dollar",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 417634
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bz.png"
  },
  {
    "category": "Countries",
    "name": "Benin",
    "attributes": {
      "capital": "Porto-Novo",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 13224860
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bj.png"
  },
  {
    "category": "Countries",
    "name": "Bhutan",
    "attributes": {
      "capital": "Thimphu",
      "currency": "Bhutanese ngultrum",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 784043
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bt.png"
  },
  {
    "category": "Countries",
    "name": "Bolivia",
    "attributes": {
      "capital": "Sucre",
      "currency": "Bolivian boliviano",
      "continent": "Americas",
      "subregion": "South America",
      "population": 11365333
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bo.png"
  },
  {
    "category": "Countries",
    "name": "Bosnia and Herzegovina",
    "attributes": {
      "capital": "Sarajevo",
      "currency": "Bosnia and Herzegovina convertible mark",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 3422000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ba.png"
  },
  {
    "category": "Countries",
    "name": "Botswana",
    "attributes": {
      "capital": "Gaborone",
      "currency": "Botswana pula",
      "continent": "Africa",
      "subregion": "Southern Africa",
      "population": 2359609
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bw.png"
  },
  {
    "category": "Countries",
    "name": "Brazil",
    "attributes": {
      "capital": "Brasília",
      "currency": "Brazilian real",
      "continent": "Americas",
      "subregion": "South America",
      "population": 213421037,
      "major_cities": [
        "São Paulo",
        "Rio de Janeiro",
        "Brasília",
        "Salvador",
        "Fortaleza",
        "Belo Horizonte"
      ],
      "largest_city": "São Paulo"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/br.png"
  },
  {
    "category": "Countries",
    "name": "Brunei",
    "attributes": {
      "capital": "Bandar Seri Begawan",
      "currency": "Brunei dollar",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 455500
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bn.png"
  },
  {
    "category": "Countries",
    "name": "Bulgaria",
    "attributes": {
      "capital": "Sofia",
      "currency": "Bulgarian lev",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 6437360
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bg.png"
  },
  {
    "category": "Countries",
    "name": "Burkina Faso",
    "attributes": {
      "capital": "Ouagadougou",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 24070553
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bf.png"
  },
  {
    "category": "Countries",
    "name": "Burundi",
    "attributes": {
      "capital": "Gitega",
      "currency": "Burundian franc",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 12332788
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/bi.png"
  },
  {
    "category": "Countries",
    "name": "Cambodia",
    "attributes": {
      "capital": "Phnom Penh",
      "currency": "Cambodian riel",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 17577760
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kh.png"
  },
  {
    "category": "Countries",
    "name": "Cameroon",
    "attributes": {
      "capital": "Yaoundé",
      "currency": "Central African CFA franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 29442327
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cm.png"
  },
  {
    "category": "Countries",
    "name": "Canada",
    "attributes": {
      "capital": "Ottawa",
      "currency": "Canadian dollar",
      "continent": "Americas",
      "subregion": "North America",
      "population": 41651653,
      "major_cities": [
        "Toronto",
        "Montreal",
        "Vancouver",
        "Calgary",
        "Ottawa"
      ],
      "largest_city": "Toronto"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ca.png"
  },
  {
    "category": "Countries",
    "name": "Cape Verde",
    "attributes": {
      "capital": "Praia",
      "currency": "Cape Verdean escudo",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 491233
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cv.png"
  },
  {
    "category": "Countries",
    "name": "Central African Republic",
    "attributes": {
      "capital": "Bangui",
      "currency": "Central African CFA franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 6470307
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cf.png"
  },
  {
    "category": "Countries",
    "name": "Chad",
    "attributes": {
      "capital": "N'Djamena",
      "currency": "Central African CFA franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 19340757
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/td.png"
  },
  {
    "category": "Countries",
    "name": "Chile",
    "attributes": {
      "capital": "Santiago",
      "currency": "Chilean peso",
      "continent": "Americas",
      "subregion": "South America",
      "population": 20206953
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cl.png"
  },
  {
    "category": "Countries",
    "name": "China",
    "attributes": {
      "capital": "Beijing",
      "currency": "Chinese yuan",
      "continent": "Asia",
      "subregion": "Eastern Asia",
      "population": 1408280000,
      "major_cities": [
        "Shanghai",
        "Beijing",
        "Chongqing",
        "Guangzhou",
        "Shenzhen",
        "Chengdu"
      ],
      "largest_city": "Shanghai"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cn.png"
  },
  {
    "category": "Countries",
    "name": "Colombia",
    "attributes": {
      "capital": "Bogotá",
      "currency": "Colombian peso",
      "continent": "Americas",
      "subregion": "South America",
      "population": 53057212,
      "major_cities": [
        "Bogotá",
        "Medellín",
        "Cali",
        "Barranquilla"
      ],
      "largest_city": "Bogotá"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/co.png"
  },
  {
    "category": "Countries",
    "name": "Comoros",
    "attributes": {
      "capital": "Moroni",
      "currency": "Comorian franc",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 919901
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/km.png"
  },
  {
    "category": "Countries",
    "name": "Costa Rica",
    "attributes": {
      "capital": "San José",
      "currency": "Costa Rican colón",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 5309625
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cr.png"
  },
  {
    "category": "Countries",
    "name": "Croatia",
    "attributes": {
      "capital": "Zagreb",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 3866233
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/hr.png"
  },
  {
    "category": "Countries",
    "name": "Cuba",
    "attributes": {
      "capital": "Havana",
      "currency": "Cuban convertible peso",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 9748007
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cu.png"
  },
  {
    "category": "Countries",
    "name": "Cyprus",
    "attributes": {
      "capital": "Nicosia",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 1442614
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cy.png"
  },
  {
    "category": "Countries",
    "name": "Czechia",
    "attributes": {
      "capital": "Prague",
      "currency": "Czech koruna",
      "continent": "Europe",
      "subregion": "Central Europe",
      "population": 10882341
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cz.png"
  },
  {
    "category": "Countries",
    "name": "Denmark",
    "attributes": {
      "capital": "Copenhagen",
      "currency": "Danish krone",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 6011488
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/dk.png"
  },
  {
    "category": "Countries",
    "name": "Djibouti",
    "attributes": {
      "capital": "Djibouti",
      "currency": "Djiboutian franc",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 1066809
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/dj.png"
  },
  {
    "category": "Countries",
    "name": "Dominica",
    "attributes": {
      "capital": "Roseau",
      "currency": "Eastern Caribbean dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 67408
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/dm.png"
  },
  {
    "category": "Countries",
    "name": "Dominican Republic",
    "attributes": {
      "capital": "Santo Domingo",
      "currency": "Dominican peso",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 10771504
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/do.png"
  },
  {
    "category": "Countries",
    "name": "DR Congo",
    "attributes": {
      "capital": "Kinshasa",
      "currency": "Congolese franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 112832000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cd.png"
  },
  {
    "category": "Countries",
    "name": "Ecuador",
    "attributes": {
      "capital": "Quito",
      "currency": "United States dollar",
      "continent": "Americas",
      "subregion": "South America",
      "population": 18103660
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ec.png"
  },
  {
    "category": "Countries",
    "name": "Egypt",
    "attributes": {
      "capital": "Cairo",
      "currency": "Egyptian pound",
      "continent": "Africa",
      "subregion": "Northern Africa",
      "population": 107271260,
      "major_cities": [
        "Cairo",
        "Alexandria",
        "Giza",
        "Shubra El Kheima"
      ],
      "largest_city": "Cairo"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/eg.png"
  },
  {
    "category": "Countries",
    "name": "El Salvador",
    "attributes": {
      "capital": "San Salvador",
      "currency": "United States dollar",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 6029976
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sv.png"
  },
  {
    "category": "Countries",
    "name": "Equatorial Guinea",
    "attributes": {
      "capital": "Ciudad de la Paz",
      "currency": "Central African CFA franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 1668768
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gq.png"
  },
  {
    "category": "Countries",
    "name": "Eritrea",
    "attributes": {
      "capital": "Asmara",
      "currency": "Eritrean nakfa",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 3607000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/er.png"
  },
  {
    "category": "Countries",
    "name": "Estonia",
    "attributes": {
      "capital": "Tallinn",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 1369995
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ee.png"
  },
  {
    "category": "Countries",
    "name": "Eswatini",
    "attributes": {
      "capital": "Mbabane",
      "currency": "Swazi lilangeni",
      "continent": "Africa",
      "subregion": "Southern Africa",
      "population": 1235549
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sz.png"
  },
  {
    "category": "Countries",
    "name": "Ethiopia",
    "attributes": {
      "capital": "Addis Ababa",
      "currency": "Ethiopian birr",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 111652998
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/et.png"
  },
  {
    "category": "Countries",
    "name": "Fiji",
    "attributes": {
      "capital": "Suva",
      "currency": "Fijian dollar",
      "continent": "Oceania",
      "subregion": "Melanesia",
      "population": 900869
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/fj.png"
  },
  {
    "category": "Countries",
    "name": "Finland",
    "attributes": {
      "capital": "Helsinki",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 5650325
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/fi.png"
  },
  {
    "category": "Countries",
    "name": "France",
    "attributes": {
      "capital": "Paris",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 66351959,
      "major_cities": [
        "Paris",
        "Marseille",
        "Lyon",
        "Toulouse",
        "Nice"
      ],
      "largest_city": "Paris"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/fr.png"
  },
  {
    "category": "Countries",
    "name": "Gabon",
    "attributes": {
      "capital": "Libreville",
      "currency": "Central African CFA franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 2469296
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ga.png"
  },
  {
    "category": "Countries",
    "name": "Gambia",
    "attributes": {
      "capital": "Banjul",
      "currency": "dalasi",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 2422712
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gm.png"
  },
  {
    "category": "Countries",
    "name": "Georgia",
    "attributes": {
      "capital": "Tbilisi",
      "currency": "lari",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 4000921
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ge.png"
  },
  {
    "category": "Countries",
    "name": "Germany",
    "attributes": {
      "capital": "Berlin",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 83491249,
      "major_cities": [
        "Berlin",
        "Hamburg",
        "Munich",
        "Cologne",
        "Frankfurt"
      ],
      "largest_city": "Berlin"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/de.png"
  },
  {
    "category": "Countries",
    "name": "Ghana",
    "attributes": {
      "capital": "Accra",
      "currency": "Ghanaian cedi",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 33742380
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gh.png"
  },
  {
    "category": "Countries",
    "name": "Greece",
    "attributes": {
      "capital": "Athens",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 10400720
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gr.png"
  },
  {
    "category": "Countries",
    "name": "Grenada",
    "attributes": {
      "capital": "St. George's",
      "currency": "Eastern Caribbean dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 109021
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gd.png"
  },
  {
    "category": "Countries",
    "name": "Guatemala",
    "attributes": {
      "capital": "Guatemala City",
      "currency": "Guatemalan quetzal",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 18079810
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gt.png"
  },
  {
    "category": "Countries",
    "name": "Guinea",
    "attributes": {
      "capital": "Conakry",
      "currency": "Guinean franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 14363931
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gn.png"
  },
  {
    "category": "Countries",
    "name": "Guyana",
    "attributes": {
      "capital": "Georgetown",
      "currency": "Guyanese dollar",
      "continent": "Americas",
      "subregion": "South America",
      "population": 772975
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gy.png"
  },
  {
    "category": "Countries",
    "name": "Haiti",
    "attributes": {
      "capital": "Port-au-Prince",
      "currency": "Haitian gourde",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 11867032
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ht.png"
  },
  {
    "category": "Countries",
    "name": "Honduras",
    "attributes": {
      "capital": "Tegucigalpa",
      "currency": "Honduran lempira",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 9892632
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/hn.png"
  },
  {
    "category": "Countries",
    "name": "Hungary",
    "attributes": {
      "capital": "Budapest",
      "currency": "Hungarian forint",
      "continent": "Europe",
      "subregion": "Central Europe",
      "population": 9539502
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/hu.png"
  },
  {
    "category": "Countries",
    "name": "Iceland",
    "attributes": {
      "capital": "Reykjavik",
      "currency": "Icelandic króna",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 391810
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/is.png"
  },
  {
    "category": "Countries",
    "name": "India",
    "attributes": {
      "capital": "New Delhi",
      "currency": "Indian rupee",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 1417492000,
      "major_cities": [
        "Mumbai",
        "Delhi",
        "Bangalore",
        "Hyderabad",
        "Ahmedabad",
        "Chennai",
        "Kolkata"
      ],
      "largest_city": "Mumbai"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/in.png"
  },
  {
    "category": "Countries",
    "name": "Indonesia",
    "attributes": {
      "capital": "Jakarta",
      "currency": "Indonesian rupiah",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 284438782,
      "major_cities": [
        "Jakarta",
        "Surabaya",
        "Bandung",
        "Medan",
        "Semarang"
      ],
      "largest_city": "Jakarta"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/id.png"
  },
  {
    "category": "Countries",
    "name": "Iran",
    "attributes": {
      "capital": "Tehran",
      "currency": "Iranian rial",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 85961000,
      "major_cities": [
        "Tehran",
        "Mashhad",
        "Isfahan",
        "Karaj",
        "Shiraz"
      ],
      "largest_city": "Tehran"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ir.png"
  },
  {
    "category": "Countries",
    "name": "Iraq",
    "attributes": {
      "capital": "Baghdad",
      "currency": "Iraqi dinar",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 46118793
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/iq.png"
  },
  {
    "category": "Countries",
    "name": "Ireland",
    "attributes": {
      "capital": "Dublin",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 5458600
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ie.png"
  },
  {
    "category": "Countries",
    "name": "Israel",
    "attributes": {
      "capital": "Jerusalem",
      "currency": "Israeli new shekel",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 10134800
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/il.png"
  },
  {
    "category": "Countries",
    "name": "Italy",
    "attributes": {
      "capital": "Rome",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 58927633,
      "major_cities": [
        "Rome",
        "Milan",
        "Naples",
        "Turin",
        "Palermo"
      ],
      "largest_city": "Rome"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/it.png"
  },
  {
    "category": "Countries",
    "name": "Ivory Coast",
    "attributes": {
      "capital": "Yamoussoukro",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 31719275
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ci.png"
  },
  {
    "category": "Countries",
    "name": "Jamaica",
    "attributes": {
      "capital": "Kingston",
      "currency": "Jamaican dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 2825544
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/jm.png"
  },
  {
    "category": "Countries",
    "name": "Japan",
    "attributes": {
      "capital": "Tokyo",
      "currency": "Japanese yen",
      "continent": "Asia",
      "subregion": "Eastern Asia",
      "population": 123210000,
      "major_cities": [
        "Tokyo",
        "Yokohama",
        "Osaka",
        "Nagoya",
        "Sapporo",
        "Fukuoka"
      ],
      "largest_city": "Tokyo"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/jp.png"
  },
  {
    "category": "Countries",
    "name": "Jordan",
    "attributes": {
      "capital": "Amman",
      "currency": "Jordanian dinar",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 11734000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/jo.png"
  },
  {
    "category": "Countries",
    "name": "Kazakhstan",
    "attributes": {
      "capital": "Astana",
      "currency": "Kazakhstani tenge",
      "continent": "Asia",
      "subregion": "Central Asia",
      "population": 20426568
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kz.png"
  },
  {
    "category": "Countries",
    "name": "Kenya",
    "attributes": {
      "capital": "Nairobi",
      "currency": "Kenyan shilling",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 53330978
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ke.png"
  },
  {
    "category": "Countries",
    "name": "Kiribati",
    "attributes": {
      "capital": "South Tarawa",
      "currency": "Australian dollar",
      "continent": "Oceania",
      "subregion": "Micronesia",
      "population": 120740
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ki.png"
  },
  {
    "category": "Countries",
    "name": "Kuwait",
    "attributes": {
      "capital": "Kuwait City",
      "currency": "Kuwaiti dinar",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 4881254
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kw.png"
  },
  {
    "category": "Countries",
    "name": "Kyrgyzstan",
    "attributes": {
      "capital": "Bishkek",
      "currency": "Kyrgyzstani som",
      "continent": "Asia",
      "subregion": "Central Asia",
      "population": 7281800
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kg.png"
  },
  {
    "category": "Countries",
    "name": "Laos",
    "attributes": {
      "capital": "Vientiane",
      "currency": "Lao kip",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 7647000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/la.png"
  },
  {
    "category": "Countries",
    "name": "Latvia",
    "attributes": {
      "capital": "Riga",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 1829000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lv.png"
  },
  {
    "category": "Countries",
    "name": "Lebanon",
    "attributes": {
      "capital": "Beirut",
      "currency": "Lebanese pound",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 5490000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lb.png"
  },
  {
    "category": "Countries",
    "name": "Lesotho",
    "attributes": {
      "capital": "Maseru",
      "currency": "Lesotho loti",
      "continent": "Africa",
      "subregion": "Southern Africa",
      "population": 2116427
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ls.png"
  },
  {
    "category": "Countries",
    "name": "Liberia",
    "attributes": {
      "capital": "Monrovia",
      "currency": "Liberian dollar",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 5248621
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lr.png"
  },
  {
    "category": "Countries",
    "name": "Libya",
    "attributes": {
      "capital": "Tripoli",
      "currency": "Libyan dinar",
      "continent": "Africa",
      "subregion": "Northern Africa",
      "population": 7459000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ly.png"
  },
  {
    "category": "Countries",
    "name": "Liechtenstein",
    "attributes": {
      "capital": "Vaduz",
      "currency": "Swiss franc",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 40900
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/li.png"
  },
  {
    "category": "Countries",
    "name": "Lithuania",
    "attributes": {
      "capital": "Vilnius",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 2894886
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lt.png"
  },
  {
    "category": "Countries",
    "name": "Luxembourg",
    "attributes": {
      "capital": "Luxembourg",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 681973
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lu.png"
  },
  {
    "category": "Countries",
    "name": "Madagascar",
    "attributes": {
      "capital": "Antananarivo",
      "currency": "Malagasy ariary",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 31727042
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mg.png"
  },
  {
    "category": "Countries",
    "name": "Malawi",
    "attributes": {
      "capital": "Lilongwe",
      "currency": "Malawian kwacha",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 20734262
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mw.png"
  },
  {
    "category": "Countries",
    "name": "Malaysia",
    "attributes": {
      "capital": "Kuala Lumpur",
      "currency": "Malaysian ringgit",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 34231700
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/my.png"
  },
  {
    "category": "Countries",
    "name": "Maldives",
    "attributes": {
      "capital": "Malé",
      "currency": "Maldivian rufiyaa",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 515132
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mv.png"
  },
  {
    "category": "Countries",
    "name": "Mali",
    "attributes": {
      "capital": "Bamako",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 22395489
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ml.png"
  },
  {
    "category": "Countries",
    "name": "Malta",
    "attributes": {
      "capital": "Valletta",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 574250
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mt.png"
  },
  {
    "category": "Countries",
    "name": "Marshall Islands",
    "attributes": {
      "capital": "Majuro",
      "currency": "United States dollar",
      "continent": "Oceania",
      "subregion": "Micronesia",
      "population": 42418
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mh.png"
  },
  {
    "category": "Countries",
    "name": "Mauritania",
    "attributes": {
      "capital": "Nouakchott",
      "currency": "Mauritanian ouguiya",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 4927532
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mr.png"
  },
  {
    "category": "Countries",
    "name": "Mauritius",
    "attributes": {
      "capital": "Port Louis",
      "currency": "Mauritian rupee",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 1243741
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mu.png"
  },
  {
    "category": "Countries",
    "name": "Mexico",
    "attributes": {
      "capital": "Mexico City",
      "currency": "Mexican peso",
      "continent": "Americas",
      "subregion": "North America",
      "population": 130575786,
      "major_cities": [
        "Mexico City",
        "Guadalajara",
        "Monterrey",
        "Puebla",
        "Tijuana"
      ],
      "largest_city": "Mexico City"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mx.png"
  },
  {
    "category": "Countries",
    "name": "Micronesia",
    "attributes": {
      "capital": "Palikir",
      "currency": "United States dollar",
      "continent": "Oceania",
      "subregion": "Micronesia",
      "population": 105564
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/fm.png"
  },
  {
    "category": "Countries",
    "name": "Moldova",
    "attributes": {
      "capital": "Chișinău",
      "currency": "Moldovan leu",
      "continent": "Europe",
      "subregion": "Eastern Europe",
      "population": 2749076
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/md.png"
  },
  {
    "category": "Countries",
    "name": "Monaco",
    "attributes": {
      "capital": "Monaco",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 38423
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mc.png"
  },
  {
    "category": "Countries",
    "name": "Mongolia",
    "attributes": {
      "capital": "Ulan Bator",
      "currency": "Mongolian tögrög",
      "continent": "Asia",
      "subregion": "Eastern Asia",
      "population": 3544835
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mn.png"
  },
  {
    "category": "Countries",
    "name": "Montenegro",
    "attributes": {
      "capital": "Podgorica",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 623327
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/me.png"
  },
  {
    "category": "Countries",
    "name": "Morocco",
    "attributes": {
      "capital": "Rabat",
      "currency": "Moroccan dirham",
      "continent": "Africa",
      "subregion": "Northern Africa",
      "population": 36828330,
      "major_cities": [
        "Casablanca",
        "Rabat",
        "Fez",
        "Marrakesh",
        "Tangier"
      ],
      "largest_city": "Casablanca"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ma.png"
  },
  {
    "category": "Countries",
    "name": "Mozambique",
    "attributes": {
      "capital": "Maputo",
      "currency": "Mozambican metical",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 34090466
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mz.png"
  },
  {
    "category": "Countries",
    "name": "Myanmar",
    "attributes": {
      "capital": "Naypyidaw",
      "currency": "Burmese kyat",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 51316756
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mm.png"
  },
  {
    "category": "Countries",
    "name": "Namibia",
    "attributes": {
      "capital": "Windhoek",
      "currency": "Namibian dollar",
      "continent": "Africa",
      "subregion": "Southern Africa",
      "population": 3022401
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/na.png"
  },
  {
    "category": "Countries",
    "name": "Nauru",
    "attributes": {
      "capital": "Yaren",
      "currency": "Australian dollar",
      "continent": "Oceania",
      "subregion": "Micronesia",
      "population": 11680
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/nr.png"
  },
  {
    "category": "Countries",
    "name": "Nepal",
    "attributes": {
      "capital": "Kathmandu",
      "currency": "Nepalese rupee",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 29911840
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/np.png"
  },
  {
    "category": "Countries",
    "name": "Netherlands",
    "attributes": {
      "capital": "Amsterdam",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 18100436,
      "major_cities": [
        "Amsterdam",
        "Rotterdam",
        "The Hague",
        "Utrecht"
      ],
      "largest_city": "Amsterdam"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/nl.png"
  },
  {
    "category": "Countries",
    "name": "New Zealand",
    "attributes": {
      "capital": "Wellington",
      "currency": "New Zealand dollar",
      "continent": "Oceania",
      "subregion": "Australia and New Zealand",
      "population": 5324700
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/nz.png"
  },
  {
    "category": "Countries",
    "name": "Nicaragua",
    "attributes": {
      "capital": "Managua",
      "currency": "Nicaraguan córdoba",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 6803886
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ni.png"
  },
  {
    "category": "Countries",
    "name": "Niger",
    "attributes": {
      "capital": "Niamey",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 26312034
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ne.png"
  },
  {
    "category": "Countries",
    "name": "Nigeria",
    "attributes": {
      "capital": "Abuja",
      "currency": "Nigerian naira",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 223800000,
      "major_cities": [
        "Lagos",
        "Kano",
        "Ibadan",
        "Abuja",
        "Port Harcourt"
      ],
      "largest_city": "Lagos"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ng.png"
  },
  {
    "category": "Countries",
    "name": "North Korea",
    "attributes": {
      "capital": "Pyongyang",
      "currency": "North Korean won",
      "continent": "Asia",
      "subregion": "Eastern Asia",
      "population": 25950000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kp.png"
  },
  {
    "category": "Countries",
    "name": "North Macedonia",
    "attributes": {
      "capital": "Skopje",
      "currency": "denar",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 1822612
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/mk.png"
  },
  {
    "category": "Countries",
    "name": "Norway",
    "attributes": {
      "capital": "Oslo",
      "currency": "Norwegian krone",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 5606944
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/no.png"
  },
  {
    "category": "Countries",
    "name": "Oman",
    "attributes": {
      "capital": "Muscat",
      "currency": "Omani rial",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 5343630
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/om.png"
  },
  {
    "category": "Countries",
    "name": "Pakistan",
    "attributes": {
      "capital": "Islamabad",
      "currency": "Pakistani rupee",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 241499431,
      "major_cities": [
        "Karachi",
        "Lahore",
        "Faisalabad",
        "Rawalpindi",
        "Islamabad"
      ],
      "largest_city": "Karachi"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pk.png"
  },
  {
    "category": "Countries",
    "name": "Palau",
    "attributes": {
      "capital": "Ngerulmud",
      "currency": "United States dollar",
      "continent": "Oceania",
      "subregion": "Micronesia",
      "population": 16733
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pw.png"
  },
  {
    "category": "Countries",
    "name": "Panama",
    "attributes": {
      "capital": "Panama City",
      "currency": "Panamanian balboa",
      "continent": "Americas",
      "subregion": "Central America",
      "population": 4064780
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pa.png"
  },
  {
    "category": "Countries",
    "name": "Papua New Guinea",
    "attributes": {
      "capital": "Port Moresby",
      "currency": "Papua New Guinean kina",
      "continent": "Oceania",
      "subregion": "Melanesia",
      "population": 11781559
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pg.png"
  },
  {
    "category": "Countries",
    "name": "Paraguay",
    "attributes": {
      "capital": "Asunción",
      "currency": "Paraguayan guaraní",
      "continent": "Americas",
      "subregion": "South America",
      "population": 6109644
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/py.png"
  },
  {
    "category": "Countries",
    "name": "Peru",
    "attributes": {
      "capital": "Lima",
      "currency": "Peruvian sol",
      "continent": "Americas",
      "subregion": "South America",
      "population": 34350244
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pe.png"
  },
  {
    "category": "Countries",
    "name": "Philippines",
    "attributes": {
      "capital": "Manila",
      "currency": "Philippine peso",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 114123600,
      "major_cities": [
        "Quezon City",
        "Manila",
        "Davao",
        "Cebu City"
      ],
      "largest_city": "Quezon City"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ph.png"
  },
  {
    "category": "Countries",
    "name": "Poland",
    "attributes": {
      "capital": "Warsaw",
      "currency": "Polish złoty",
      "continent": "Europe",
      "subregion": "Central Europe",
      "population": 37392000,
      "major_cities": [
        "Warsaw",
        "Kraków",
        "Łódź",
        "Wrocław",
        "Poznań"
      ],
      "largest_city": "Warsaw"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pl.png"
  },
  {
    "category": "Countries",
    "name": "Portugal",
    "attributes": {
      "capital": "Lisbon",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 10749635
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/pt.png"
  },
  {
    "category": "Countries",
    "name": "Qatar",
    "attributes": {
      "capital": "Doha",
      "currency": "Qatari riyal",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 3173024
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/qa.png"
  },
  {
    "category": "Countries",
    "name": "Republic of the Congo",
    "attributes": {
      "capital": "Brazzaville",
      "currency": "Central African CFA franc",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 6142180
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/cg.png"
  },
  {
    "category": "Countries",
    "name": "Romania",
    "attributes": {
      "capital": "Bucharest",
      "currency": "Romanian leu",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 19036031
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ro.png"
  },
  {
    "category": "Countries",
    "name": "Russia",
    "attributes": {
      "capital": "Moscow",
      "currency": "Russian ruble",
      "continent": "Europe",
      "subregion": "Eastern Europe",
      "population": 146028325,
      "major_cities": [
        "Moscow",
        "Saint Petersburg",
        "Novosibirsk",
        "Yekaterinburg",
        "Kazan"
      ],
      "largest_city": "Moscow"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ru.png"
  },
  {
    "category": "Countries",
    "name": "Rwanda",
    "attributes": {
      "capital": "Kigali",
      "currency": "Rwandan franc",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 14104969
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/rw.png"
  },
  {
    "category": "Countries",
    "name": "Saint Kitts and Nevis",
    "attributes": {
      "capital": "Basseterre",
      "currency": "Eastern Caribbean dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 51320
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kn.png"
  },
  {
    "category": "Countries",
    "name": "Saint Lucia",
    "attributes": {
      "capital": "Castries",
      "currency": "Eastern Caribbean dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 184100
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lc.png"
  },
  {
    "category": "Countries",
    "name": "Saint Vincent and the Grenadines",
    "attributes": {
      "capital": "Kingstown",
      "currency": "Eastern Caribbean dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 110872
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/vc.png"
  },
  {
    "category": "Countries",
    "name": "Samoa",
    "attributes": {
      "capital": "Apia",
      "currency": "Samoan tālā",
      "continent": "Oceania",
      "subregion": "Polynesia",
      "population": 205557
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ws.png"
  },
  {
    "category": "Countries",
    "name": "San Marino",
    "attributes": {
      "capital": "City of San Marino",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 34132
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sm.png"
  },
  {
    "category": "Countries",
    "name": "São Tomé and Príncipe",
    "attributes": {
      "capital": "São Tomé",
      "currency": "São Tomé and Príncipe dobra",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 209607
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/st.png"
  },
  {
    "category": "Countries",
    "name": "Saudi Arabia",
    "attributes": {
      "capital": "Riyadh",
      "currency": "Saudi riyal",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 35300280,
      "major_cities": [
        "Riyadh",
        "Jeddah",
        "Mecca",
        "Medina",
        "Dammam"
      ],
      "largest_city": "Riyadh"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sa.png"
  },
  {
    "category": "Countries",
    "name": "Senegal",
    "attributes": {
      "capital": "Dakar",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 18593258
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sn.png"
  },
  {
    "category": "Countries",
    "name": "Serbia",
    "attributes": {
      "capital": "Belgrade",
      "currency": "Serbian dinar",
      "continent": "Europe",
      "subregion": "Southeast Europe",
      "population": 6567783
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/rs.png"
  },
  {
    "category": "Countries",
    "name": "Seychelles",
    "attributes": {
      "capital": "Victoria",
      "currency": "Seychellois rupee",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 122729
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sc.png"
  },
  {
    "category": "Countries",
    "name": "Sierra Leone",
    "attributes": {
      "capital": "Freetown",
      "currency": "Leone",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 9077691
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sl.png"
  },
  {
    "category": "Countries",
    "name": "Singapore",
    "attributes": {
      "capital": "Singapore",
      "currency": "Singapore dollar",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 6110200
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sg.png"
  },
  {
    "category": "Countries",
    "name": "Slovakia",
    "attributes": {
      "capital": "Bratislava",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Central Europe",
      "population": 5413813
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sk.png"
  },
  {
    "category": "Countries",
    "name": "Slovenia",
    "attributes": {
      "capital": "Ljubljana",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Central Europe",
      "population": 2130638
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/si.png"
  },
  {
    "category": "Countries",
    "name": "Solomon Islands",
    "attributes": {
      "capital": "Honiara",
      "currency": "Solomon Islands dollar",
      "continent": "Oceania",
      "subregion": "Melanesia",
      "population": 750325
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sb.png"
  },
  {
    "category": "Countries",
    "name": "Somalia",
    "attributes": {
      "capital": "Mogadishu",
      "currency": "Somali shilling",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 19655000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/so.png"
  },
  {
    "category": "Countries",
    "name": "South Africa",
    "attributes": {
      "capital": "Pretoria",
      "currency": "South African rand",
      "continent": "Africa",
      "subregion": "Southern Africa",
      "population": 63100945,
      "major_cities": [
        "Johannesburg",
        "Cape Town",
        "Durban",
        "Pretoria"
      ],
      "largest_city": "Johannesburg"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/za.png"
  },
  {
    "category": "Countries",
    "name": "South Korea",
    "attributes": {
      "capital": "Seoul",
      "currency": "South Korean won",
      "continent": "Asia",
      "subregion": "Eastern Asia",
      "population": 51159889,
      "major_cities": [
        "Seoul",
        "Busan",
        "Incheon",
        "Daegu",
        "Daejeon"
      ],
      "largest_city": "Seoul"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/kr.png"
  },
  {
    "category": "Countries",
    "name": "South Sudan",
    "attributes": {
      "capital": "Juba",
      "currency": "South Sudanese pound",
      "continent": "Africa",
      "subregion": "Middle Africa",
      "population": 15786898
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ss.png"
  },
  {
    "category": "Countries",
    "name": "Spain",
    "attributes": {
      "capital": "Madrid",
      "currency": "euro",
      "continent": "Europe",
      "subregion": "Southern Europe",
      "population": 49315949,
      "major_cities": [
        "Madrid",
        "Barcelona",
        "Valencia",
        "Seville",
        "Zaragoza"
      ],
      "largest_city": "Madrid"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/es.png"
  },
  {
    "category": "Countries",
    "name": "Sri Lanka",
    "attributes": {
      "capital": "Sri Jayawardenepura Kotte",
      "currency": "Sri Lankan rupee",
      "continent": "Asia",
      "subregion": "Southern Asia",
      "population": 21763170
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/lk.png"
  },
  {
    "category": "Countries",
    "name": "Sudan",
    "attributes": {
      "capital": "Khartoum",
      "currency": "Sudanese pound",
      "continent": "Africa",
      "subregion": "Northern Africa",
      "population": 51662000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sd.png"
  },
  {
    "category": "Countries",
    "name": "Suriname",
    "attributes": {
      "capital": "Paramaribo",
      "currency": "Surinamese dollar",
      "continent": "Americas",
      "subregion": "South America",
      "population": 616500
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sr.png"
  },
  {
    "category": "Countries",
    "name": "Sweden",
    "attributes": {
      "capital": "Stockholm",
      "currency": "Swedish krona",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 10605098
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/se.png"
  },
  {
    "category": "Countries",
    "name": "Switzerland",
    "attributes": {
      "capital": "Bern",
      "currency": "Swiss franc",
      "continent": "Europe",
      "subregion": "Western Europe",
      "population": 9082848
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ch.png"
  },
  {
    "category": "Countries",
    "name": "Syria",
    "attributes": {
      "capital": "Damascus",
      "currency": "Syrian pound",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 25620000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/sy.png"
  },
  {
    "category": "Countries",
    "name": "Tajikistan",
    "attributes": {
      "capital": "Dushanbe",
      "currency": "Tajikistani somoni",
      "continent": "Asia",
      "subregion": "Central Asia",
      "population": 10499000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tj.png"
  },
  {
    "category": "Countries",
    "name": "Tanzania",
    "attributes": {
      "capital": "Dodoma",
      "currency": "Tanzanian shilling",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 68153004
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tz.png"
  },
  {
    "category": "Countries",
    "name": "Thailand",
    "attributes": {
      "capital": "Bangkok",
      "currency": "Thai baht",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 65859640,
      "major_cities": [
        "Bangkok",
        "Nonthaburi",
        "Nakhon Ratchasima",
        "Chiang Mai"
      ],
      "largest_city": "Bangkok"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/th.png"
  },
  {
    "category": "Countries",
    "name": "Timor-Leste",
    "attributes": {
      "capital": "Dili",
      "currency": "United States dollar",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 1391221
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tl.png"
  },
  {
    "category": "Countries",
    "name": "Togo",
    "attributes": {
      "capital": "Lomé",
      "currency": "West African CFA franc",
      "continent": "Africa",
      "subregion": "Western Africa",
      "population": 8095498
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tg.png"
  },
  {
    "category": "Countries",
    "name": "Tonga",
    "attributes": {
      "capital": "Nuku'alofa",
      "currency": "Tongan paʻanga",
      "continent": "Oceania",
      "subregion": "Polynesia",
      "population": 100179
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/to.png"
  },
  {
    "category": "Countries",
    "name": "Trinidad and Tobago",
    "attributes": {
      "capital": "Port of Spain",
      "currency": "Trinidad and Tobago dollar",
      "continent": "Americas",
      "subregion": "Caribbean",
      "population": 1367764
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tt.png"
  },
  {
    "category": "Countries",
    "name": "Tunisia",
    "attributes": {
      "capital": "Tunis",
      "currency": "Tunisian dinar",
      "continent": "Africa",
      "subregion": "Northern Africa",
      "population": 11972169
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tn.png"
  },
  {
    "category": "Countries",
    "name": "Turkey",
    "attributes": {
      "capital": "Ankara",
      "currency": "Turkish lira",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 85664944,
      "major_cities": [
        "Istanbul",
        "Ankara",
        "Izmir",
        "Bursa",
        "Adana"
      ],
      "largest_city": "Istanbul"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tr.png"
  },
  {
    "category": "Countries",
    "name": "Turkmenistan",
    "attributes": {
      "capital": "Ashgabat",
      "currency": "Turkmenistan manat",
      "continent": "Asia",
      "subregion": "Central Asia",
      "population": 7057841
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tm.png"
  },
  {
    "category": "Countries",
    "name": "Tuvalu",
    "attributes": {
      "capital": "Funafuti",
      "currency": "Australian dollar",
      "continent": "Oceania",
      "subregion": "Polynesia",
      "population": 10643
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/tv.png"
  },
  {
    "category": "Countries",
    "name": "Uganda",
    "attributes": {
      "capital": "Kampala",
      "currency": "Ugandan shilling",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 45905417
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ug.png"
  },
  {
    "category": "Countries",
    "name": "Ukraine",
    "attributes": {
      "capital": "Kyiv",
      "currency": "Ukrainian hryvnia",
      "continent": "Europe",
      "subregion": "Eastern Europe",
      "population": 32862000,
      "major_cities": [
        "Kyiv",
        "Kharkiv",
        "Odesa",
        "Dnipro",
        "Lviv"
      ],
      "largest_city": "Kyiv"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ua.png"
  },
  {
    "category": "Countries",
    "name": "United Arab Emirates",
    "attributes": {
      "capital": "Abu Dhabi",
      "currency": "United Arab Emirates dirham",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 11294243
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ae.png"
  },
  {
    "category": "Countries",
    "name": "United Kingdom",
    "attributes": {
      "capital": "London",
      "currency": "British pound",
      "continent": "Europe",
      "subregion": "Northern Europe",
      "population": 69281437,
      "major_cities": [
        "London",
        "Birmingham",
        "Manchester",
        "Glasgow",
        "Liverpool"
      ],
      "largest_city": "London"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/gb.png"
  },
  {
    "category": "Countries",
    "name": "United States",
    "attributes": {
      "capital": "Washington, D.C.",
      "currency": "United States dollar",
      "continent": "Americas",
      "subregion": "North America",
      "population": 340110988,
      "major_cities": [
        "New York City",
        "Los Angeles",
        "Chicago",
        "Houston",
        "Phoenix",
        "Philadelphia"
      ],
      "largest_city": "New York City"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/us.png"
  },
  {
    "category": "Countries",
    "name": "Uruguay",
    "attributes": {
      "capital": "Montevideo",
      "currency": "Uruguayan peso",
      "continent": "Americas",
      "subregion": "South America",
      "population": 3499451
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/uy.png"
  },
  {
    "category": "Countries",
    "name": "Uzbekistan",
    "attributes": {
      "capital": "Tashkent",
      "currency": "Uzbekistani soʻm",
      "continent": "Asia",
      "subregion": "Central Asia",
      "population": 37859698
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/uz.png"
  },
  {
    "category": "Countries",
    "name": "Vanuatu",
    "attributes": {
      "capital": "Port Vila",
      "currency": "Vanuatu vatu",
      "continent": "Oceania",
      "subregion": "Melanesia",
      "population": 321409
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/vu.png"
  },
  {
    "category": "Countries",
    "name": "Venezuela",
    "attributes": {
      "capital": "Caracas",
      "currency": "Venezuelan bolívar soberano",
      "continent": "Americas",
      "subregion": "South America",
      "population": 28517000
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ve.png"
  },
  {
    "category": "Countries",
    "name": "Vietnam",
    "attributes": {
      "capital": "Hanoi",
      "currency": "Vietnamese đồng",
      "continent": "Asia",
      "subregion": "South-Eastern Asia",
      "population": 101343800,
      "major_cities": [
        "Ho Chi Minh City",
        "Hanoi",
        "Haiphong",
        "Da Nang"
      ],
      "largest_city": "Ho Chi Minh City"
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/vn.png"
  },
  {
    "category": "Countries",
    "name": "Yemen",
    "attributes": {
      "capital": "Sana'a",
      "currency": "Yemeni rial",
      "continent": "Asia",
      "subregion": "Western Asia",
      "population": 32684503
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/ye.png"
  },
  {
    "category": "Countries",
    "name": "Zambia",
    "attributes": {
      "capital": "Lusaka",
      "currency": "Zambian kwacha",
      "continent": "Africa",
      "subregion": "Eastern Africa",
      "population": 19693423
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/zm.png"
  },
  {
    "category": "Countries",
    "name": "Zimbabwe",
    "attributes": {
      "capital": "Harare",
      "currency": "Zimbabwean dollar",
      "continent": "Africa",
      "subregion": "Southern Africa",
      "population": 17073087
    },
    "mediaType": "image",
    "mediaUrl": "https://flagcdn.com/w320/zw.png"
  }
];

module.exports = { countryEntities };
