/**
 * Builds templates/seedMedia.js with two media-question datasets:
 *  - anthemEntities : "Which country's anthem is this?" (audio, from Wikipedia media-list)
 *  - clipEntities   : "Which animal is in this clip?"   (video, public-domain webm from Commons)
 * Run: node scripts/buildMedia.js
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const OUT = path.join(__dirname, "..", "templates", "seedMedia.js");
const { countryEntities } = require("../templates/seedEntities");
const continentOf = {};
for (const c of countryEntities) continentOf[c.name] = c.attributes.continent || "";

const UA = "QuizzardSeedBot/1.0 (https://github.com/quizzard; seed)";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function getText(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": UA } }, (res) => {
        let d = "";
        res.on("data", (c) => (d += c));
        res.on("end", () => resolve({ status: res.statusCode, body: d }));
      })
      .on("error", reject);
  });
}

async function getJsonRetry(url) {
  for (let a = 0; a < 4; a++) {
    const { status, body } = await getText(url);
    if (status === 200 && body.trim().startsWith("{")) return JSON.parse(body);
    await sleep(1000 * (a + 1));
  }
  return null;
}

const filePath = (fileTitle) =>
  "https://commons.wikimedia.org/wiki/Special:FilePath/" +
  encodeURIComponent(fileTitle.replace(/^File:/, "").replace(/ /g, "_"));

const ANTHEM_COUNTRIES = [
  "India", "United States", "France", "Germany", "Japan", "Brazil", "Italy", "Spain",
  "Russia", "China", "Canada", "Australia", "Mexico", "Argentina", "Egypt", "Turkey",
  "Greece", "Portugal", "Netherlands", "Sweden", "Poland", "South Africa", "Kenya",
  "Nigeria", "Thailand", "Indonesia", "Pakistan", "Bangladesh", "Israel", "Norway",
];

async function buildAnthems() {
  const out = [];
  for (const country of ANTHEM_COUNTRIES) {
    const data = await getJsonRetry(
      "https://en.wikipedia.org/api/rest_v1/page/media-list/" + encodeURIComponent(country)
    );
    const audio = (data?.items || []).filter((i) => i.type === "audio");
    if (!audio.length) {
      console.warn(`  no anthem audio: ${country}`);
      await sleep(250);
      continue;
    }
    const pick = audio.find((a) => /anthem|jana|marseillaise|hymn/i.test(a.title)) || audio[0];
    // Resolve the DIRECT upload URL (audioplayers on web can't follow the Special:FilePath redirect).
    const info = await getJsonRetry(
      "https://commons.wikimedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=url&titles=" +
        encodeURIComponent(pick.title)
    );
    let directUrl = null;
    for (const k of Object.keys(info?.query?.pages || {})) {
      const ii = info.query.pages[k].imageinfo?.[0];
      if (ii?.url) {
        directUrl = ii.url;
        break;
      }
    }
    out.push({
      category: "Anthems",
      name: country,
      attributes: { continent: continentOf[country] || "" },
      mediaType: "audio",
      mediaUrl: directUrl || filePath(pick.title),
    });
    console.log(`✓ anthem ${country}`);
    await sleep(250);
  }
  return out;
}

const ANIMALS = ["Elephant", "Lion", "Tiger", "Giraffe", "Penguin", "Kangaroo", "Dolphin", "Zebra"];

async function buildClips() {
  const out = [];
  for (const animal of ANIMALS) {
    const data = await getJsonRetry(
      "https://commons.wikimedia.org/w/api.php?action=query&format=json&generator=search&gsrsearch=" +
        encodeURIComponent(animal + " video") +
        "&gsrnamespace=6&gsrlimit=8&prop=imageinfo&iiprop=url|mime"
    );
    const pages = data?.query?.pages || {};
    let url = null;
    for (const k of Object.keys(pages)) {
      const ii = pages[k].imageinfo?.[0];
      if (ii && ii.mime === "video/webm") {
        url = ii.url;
        break;
      }
    }
    if (!url) {
      console.warn(`  no webm clip: ${animal}`);
      await sleep(250);
      continue;
    }
    out.push({
      category: "Nature Clips",
      name: animal,
      attributes: {},
      mediaType: "video",
      mediaUrl: url,
    });
    console.log(`✓ clip ${animal}`);
    await sleep(250);
  }
  return out;
}

(async () => {
  const anthemEntities = await buildAnthems();
  const clipEntities = await buildClips();
  const header = `// AUTO-GENERATED by scripts/buildMedia.js — do not edit by hand.
// anthems: ${anthemEntities.length}, clips: ${clipEntities.length}\n\n`;
  fs.writeFileSync(
    OUT,
    header +
      `const anthemEntities = ${JSON.stringify(anthemEntities, null, 2)};\n\n` +
      `const clipEntities = ${JSON.stringify(clipEntities, null, 2)};\n\n` +
      `module.exports = { anthemEntities, clipEntities };\n`
  );
  console.log(`\nWrote ${anthemEntities.length} anthems + ${clipEntities.length} clips to ${OUT}`);
})();
