/**
 * Builds templates/seedPersonalities.js: photo-based "Who is this?" entities for
 * Bollywood / Hollywood / Sports, using Wikipedia lead portraits.
 * Run: node scripts/buildPersonalities.js
 * Names must match Wikipedia article titles. People without a usable photo are skipped.
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const OUT = path.join(__dirname, "..", "templates", "seedPersonalities.js");

const PEOPLE = {
  Bollywood: [
    "Amitabh Bachchan", "Shah Rukh Khan", "Aamir Khan", "Salman Khan", "Deepika Padukone",
    "Priyanka Chopra", "Aishwarya Rai", "Ranbir Kapoor", "Ranveer Singh", "Alia Bhatt",
    "Hrithik Roshan", "Akshay Kumar", "Kareena Kapoor", "Katrina Kaif", "Madhuri Dixit",
    "Anil Kapoor", "Ajay Devgn", "Vidya Balan", "Kangana Ranaut", "Nawazuddin Siddiqui",
    "Irrfan Khan", "Rani Mukerji", "Saif Ali Khan", "Vicky Kaushal", "Rajkummar Rao",
    "Kajol", "Varun Dhawan", "Shahid Kapoor", "Anushka Sharma", "Ayushmann Khurrana",
  ],
  Hollywood: [
    "Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Tom Hanks", "Robert Downey Jr.",
    "Scarlett Johansson", "Meryl Streep", "Denzel Washington", "Will Smith", "Johnny Depp",
    "Angelina Jolie", "Jennifer Lawrence", "Morgan Freeman", "Christian Bale", "Matt Damon",
    "Natalie Portman", "Anne Hathaway", "Hugh Jackman", "Chris Evans", "Chris Hemsworth",
    "Keanu Reeves", "Samuel L. Jackson", "Emma Stone", "Ryan Reynolds", "Margot Robbie",
    "Al Pacino", "Robert De Niro", "Steven Spielberg", "Christopher Nolan", "Quentin Tarantino",
  ],
  Sports: [
    "Lionel Messi", "Cristiano Ronaldo", "Virat Kohli", "Sachin Tendulkar", "MS Dhoni",
    "Roger Federer", "Rafael Nadal", "Novak Djokovic", "Serena Williams", "Usain Bolt",
    "LeBron James", "Michael Jordan", "Tiger Woods", "Lewis Hamilton", "Neymar",
    "Kylian Mbappé", "Tom Brady", "Stephen Curry", "Rohit Sharma", "Kobe Bryant",
    "Diego Maradona", "Pelé", "Muhammad Ali", "Michael Phelps", "P. V. Sindhu",
    "Sania Mirza", "Mike Tyson", "Ronaldinho", "Zinedine Zidane", "Saina Nehwal",
  ],
};

// Wikipedia throttles generic clients; use a descriptive UA and back off on failure.
const UA = "QuizzardSeedBot/1.0 (https://github.com/quizzard; seed script)";

function getText(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": UA } }, (res) => {
        let d = "";
        res.on("data", (c) => (d += c));
        res.on("end", () => resolve({ status: res.statusCode, body: d }));
      })
      .on("error", reject);
  });
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function photoFor(title) {
  const api =
    "https://en.wikipedia.org/w/api.php?action=query&format=json&prop=pageimages&piprop=thumbnail&pithumbsize=500&titles=" +
    encodeURIComponent(title);
  for (let attempt = 0; attempt < 4; attempt++) {
    const { status, body } = await getText(api);
    if (status === 200 && body.trim().startsWith("{")) {
      const pages = JSON.parse(body)?.query?.pages || {};
      for (const k of Object.keys(pages)) {
        const src = pages[k]?.thumbnail?.source;
        if (src) return src;
      }
      return null; // valid response, just no image
    }
    // throttled or transient: wait longer each time
    await sleep(1000 * (attempt + 1));
  }
  throw new Error("rate-limited after retries");
}

(async () => {
  const entities = [];
  for (const [category, names] of Object.entries(PEOPLE)) {
    for (const name of names) {
      try {
        const url = await photoFor(name);
        if (!url) {
          console.warn(`  no photo: ${category} / ${name}`);
          continue;
        }
        entities.push({
          category,
          name,
          attributes: {},
          mediaType: "image",
          mediaUrl: url,
        });
        console.log(`✓ ${category} / ${name}`);
      } catch (e) {
        console.warn(`  ✗ ${name}: ${e.message}`);
      }
      await sleep(350);
    }
  }
  const byCat = {};
  for (const e of entities) byCat[e.category] = (byCat[e.category] || 0) + 1;
  const header = `// AUTO-GENERATED by scripts/buildPersonalities.js — do not edit by hand.
// Wikipedia portrait photos. Counts: ${JSON.stringify(byCat)}\n\n`;
  fs.writeFileSync(
    OUT,
    header + `const personalityEntities = ${JSON.stringify(entities, null, 2)};\n\nmodule.exports = { personalityEntities };\n`
  );
  console.log(`\nWrote ${entities.length} personalities to ${OUT}`);
})();
