/**
 * Deep curated question sets (50-60 each) for the priority categories:
 * Friends, The Big Bang Theory, Taarak Mehta Ka Ooltah Chashmah, Bollywood Trivia.
 * Run: node scripts/seedPriorityShows.js  (replaces these four categories)
 * Item format: [question, correctAnswer, [wrong1, wrong2, wrong3], level]
 */
require("dotenv").config();
const mongoose = require("mongoose");
const Question = require("../models/Question");

const LEVEL_CONFIG = { easy: { xp: 20, time: 12 }, medium: { xp: 40, time: 10 }, hard: { xp: 80, time: 8 } };

const SETS = {
  Friends: [
    ["What is the name of Ross's pet monkey?", "Marcel", ["Coco", "Bananas", "Mr. Winkle"], "easy"],
    ["What is Joey's signature pick-up line?", "How you doin'?", ["Hey gorgeous", "What's up?", "Nice to meet ya"], "easy"],
    ["Where do the friends usually hang out?", "Central Perk", ["Café Nervosa", "The Grind", "Java Joe's"], "easy"],
    ["What is Phoebe's famous song about a feline?", "Smelly Cat", ["Crazy Cat", "Stinky Kitty", "Sticky Cat"], "easy"],
    ["What is Ross's profession?", "Paleontologist", ["Lawyer", "Architect", "Chemist"], "easy"],
    ["What does Ross repeatedly insist during his split with Rachel?", "We were on a break", ["It was a mistake", "We were finished", "It meant nothing"], "easy"],
    ["What is the name of Ross and Rachel's daughter?", "Emma", ["Ella", "Emily", "Erica"], "medium"],
    ["Who is Phoebe's identical twin sister?", "Ursula", ["Ursa", "Una", "Ulrika"], "medium"],
    ["What does Joey famously refuse to do with his food?", "Share it", ["Cook it", "Pay for it", "Finish it"], "easy"],
    ["Who works at Central Perk and is secretly in love with Rachel?", "Gunther", ["Gary", "Gunner", "Glen"], "medium"],
    ["In which city is Friends set?", "New York City", ["Boston", "Chicago", "Los Angeles"], "easy"],
    ["What is Monica's profession?", "Chef", ["Teacher", "Nurse", "Photographer"], "medium"],
    ["What word do they shout while moving a couch upstairs?", "Pivot", ["Turn", "Lift", "Twist"], "easy"],
    ["Whom does Ross drunkenly marry in Las Vegas?", "Rachel", ["Emily", "Monica", "Phoebe"], "medium"],
    ["Who does Phoebe marry?", "Mike Hannigan", ["David", "Gary", "Duncan"], "medium"],
    ["Which actor plays Phoebe's husband Mike?", "Paul Rudd", ["Tom Selleck", "Jon Favreau", "Bruce Willis"], "hard"],
    ["What is the name of Ross's son?", "Ben", ["Owen", "Jack", "Joey Jr."], "medium"],
    ["Ross's first wife Carol leaves him for a woman named?", "Susan", ["Sophie", "Sandra", "Sarah"], "medium"],
    ["Whom does Rachel leave at the altar in the pilot?", "Barry", ["Paolo", "Joshua", "Tag"], "medium"],
    ["What soap opera character does Joey play?", "Dr. Drake Ramoray", ["Dr. John Carter", "Dr. Doug Ross", "Dr. Mark Greene"], "medium"],
    ["On which soap opera does Joey act?", "Days of Our Lives", ["General Hospital", "The Bold and the Beautiful", "All My Children"], "hard"],
    ["What is Joey's bedtime stuffed-penguin pal called?", "Hugsy", ["Snuggles", "Pengy", "Waddles"], "hard"],
    ["What is Janice's grating catchphrase?", "Oh. My. God!", ["No way!", "Get out!", "Seriously?"], "easy"],
    ["Who officiates Monica and Chandler's wedding?", "Joey", ["Ross", "Gunther", "Phoebe"], "medium"],
    ["Monica and Chandler's twins are born to a surrogate named?", "Erica", ["Emma", "Emily", "Edie"], "hard"],
    ["What are Monica and Chandler's twins named?", "Jack and Erica", ["Ben and Emma", "Frank and Alice", "Leslie and Chandler"], "hard"],
    ["What pets do Joey and Chandler keep in their apartment?", "A chick and a duck", ["A cat and a dog", "Two fish", "A parrot"], "medium"],
    ["What fake name does Phoebe love to use as an alias?", "Regina Phalange", ["Ken Adams", "Princess Consuela", "Crap Bag"], "medium"],
    ["What new name does Phoebe legally take after marrying Mike?", "Princess Consuela Banana-Hammock", ["Regina Phalange", "Phoebe Buffay-Hannigan", "Lily Buffay"], "hard"],
    ["What does Ross claim 'Unagi' means?", "A state of total awareness", ["A type of sushi", "Inner peace", "True love"], "hard"],
    ["Who ate Ross's prized Thanksgiving leftover sandwich?", "His boss", ["Joey", "Chandler", "Gunther"], "hard"],
    ["What is the special ingredient in Ross's sandwich, the 'Moist Maker'?", "A gravy-soaked bread slice", ["Extra mayo", "Cranberry jelly", "Melted cheese"], "hard"],
    ["Chandler works in a job involving statistics and data; what does Rachel guess it is?", "A transponster", ["A transponder", "An analyst", "A processor"], "hard"],
    ["Which of Rachel's sisters is played by Reese Witherspoon?", "Jill", ["Amy", "Joanna", "Mindy"], "hard"],
    ["What is the name of Ross and Monica's father?", "Jack Geller", ["Frank", "Leonard", "Charles"], "medium"],
    ["What is the name of Ross and Monica's mother?", "Judy Geller", ["Nora", "Gloria", "Sandra"], "medium"],
    ["Chandler's father performs a drag show in Las Vegas under what name?", "Helena Handbasket", ["Lady Marmalade", "Miss Chanandler", "Gloria Vanderbilt"], "hard"],
    ["What is Chandler's middle name?", "Muriel", ["Maurice", "Martin", "Murray"], "hard"],
    ["What does Monica organize obsessively?", "Everything (she's a neat freak)", ["Her record collection", "Her shoes only", "Nothing"], "easy"],
    ["What instrument does Phoebe play at Central Perk?", "Guitar", ["Piano", "Violin", "Ukulele"], "easy"],
    ["Who is Rachel's wealthy, boring boyfriend that she nearly moves to Paris instead of?", "Joshua", ["Tag", "Paolo", "Barry"], "hard"],
    ["What is the name of Rachel's much-younger assistant she dates?", "Tag", ["Josh", "Paolo", "Gavin"], "hard"],
    ["What nationality is Paolo, Rachel's early fling?", "Italian", ["Spanish", "French", "Greek"], "medium"],
    ["What is Gunther's hair color?", "Bleached blond", ["Black", "Red", "Brown"], "easy"],
    ["Which friend is the most messy/laid-back roommate?", "Joey", ["Monica", "Ross", "Chandler"], "easy"],
    ["What does Ross get that he is very embarrassed about (a cosmetic disaster)?", "A spray tan gone wrong", ["A bad haircut", "A face tattoo", "A nose job"], "medium"],
    ["What is the name of the building superintendent-style game—what football trophy do the Gellers compete for?", "The Geller Cup", ["The Turkey Bowl", "The Geller Trophy", "The Family Cup"], "hard"],
    ["Who was Chandler's annoying roommate before Joey?", "Kip", ["Eddie", "Gary", "Doug"], "hard"],
    ["After Joey moves out, who briefly becomes Chandler's unhinged roommate?", "Eddie", ["Kip", "Gunther", "Mr. Heckles"], "hard"],
    ["What is the name of the friends' grumpy downstairs neighbor (early seasons)?", "Mr. Heckles", ["Mr. Treeger", "Mr. Geller", "Mr. Bing"], "hard"],
    ["What is Joey's acting agent's name?", "Estelle", ["Gladys", "Doris", "Edna"], "hard"],
    ["What does Phoebe do for a living?", "Massage therapist", ["Waitress", "Singer only", "Chef"], "medium"],
    ["Which friend is afraid of dogs?", "Chandler", ["Ross", "Joey", "Monica"], "medium"],
    ["Where does Rachel get a job in fashion late in the series (the offer to Paris)?", "Louis Vuitton", ["Gucci", "Prada", "Chanel"], "hard"],
  ],
  "The Big Bang Theory": [
    ["What is Sheldon's signature catchphrase?", "Bazinga!", ["Gotcha!", "Boom!", "Surprise!"], "easy"],
    ["What does Sheldon call his designated couch seat?", "His spot", ["His throne", "His zone", "His corner"], "easy"],
    ["What field do Leonard and Sheldon work in?", "Physics", ["Chemistry", "Biology", "Engineering"], "easy"],
    ["What is Howard Wolowitz's profession?", "Aerospace engineer", ["Physicist", "Doctor", "Astronomer"], "medium"],
    ["Why can't Raj initially speak to women?", "Selective mutism without alcohol", ["A stutter", "Shyness only", "He doesn't speak English"], "medium"],
    ["At which university do the characters work?", "Caltech", ["MIT", "Stanford", "Harvard"], "easy"],
    ["What song does Sheldon love to be sung when he's sick?", "Soft Kitty", ["Sleepy Cat", "Warm Kitty", "Lullaby Cat"], "easy"],
    ["What is Penny's job when the series begins?", "Waitress at The Cheesecake Factory", ["Actress only", "Bartender", "Receptionist"], "medium"],
    ["What is Amy Farrah Fowler's scientific field?", "Neurobiology", ["Physics", "Astronomy", "Geology"], "medium"],
    ["What is Sheldon's twin sister's name?", "Missy", ["Mandy", "Megan", "Molly"], "hard"],
    ["Who owns the comic book store?", "Stuart", ["Steve", "Stan", "Simon"], "medium"],
    ["Which character travels to the International Space Station?", "Howard", ["Leonard", "Raj", "Sheldon"], "medium"],
    ["In which California city is the show set?", "Pasadena", ["San Diego", "San Francisco", "Sacramento"], "hard"],
    ["What does Sheldon do when knocking on Penny's door?", "Knock three times saying her name each time", ["Ring once", "Knock loudly twice", "Text first"], "easy"],
    ["What is Howard's mother famous for in the show?", "Her loud off-screen voice", ["Her cooking blog", "Her singing", "Her job at NASA"], "medium"],
    ["What kind of doctorate does Sheldon hold?", "PhD (and an Sc.D.)", ["MD", "He has none", "Honorary only"], "medium"],
    ["Whom does Howard marry?", "Bernadette", ["Penny", "Amy", "Emily"], "easy"],
    ["What is Bernadette's profession?", "Microbiologist / pharmaceutical researcher", ["Teacher", "Nurse", "Lawyer"], "medium"],
    ["What is the name of Sheldon and Amy's relationship agreement?", "The Relationship Agreement", ["The Roommate Pact", "The Couple Contract", "The Bond"], "medium"],
    ["Sheldon and Amy jointly win which prize late in the series?", "The Nobel Prize (in Physics)", ["The Fields Medal", "The Turing Award", "An Emmy"], "hard"],
    ["What is the name of Howard's robotic hand mishap involving... what device does he get stuck?", "A robotic arm", ["A 3D printer", "A drone", "A Mars rover"], "hard"],
    ["What comic-based superhero does Sheldon dress as most fondly (his favorite color/character)?", "The Flash", ["Batman", "Superman", "Green Lantern"], "medium"],
    ["What is the name of the roommate agreement Sheldon makes Leonard sign?", "The Roommate Agreement", ["The Apartment Pact", "The Living Contract", "The Roommate Code"], "easy"],
    ["What food does the gang order almost every week?", "Takeout (Thai/Chinese)", ["Pizza only", "Burgers", "Sushi only"], "easy"],
    ["What is Raj's full first name?", "Rajesh", ["Ravi", "Rohan", "Ranjit"], "medium"],
    ["What is Raj's surname?", "Koothrappali", ["Patel", "Nair", "Kapoor"], "medium"],
    ["What is the name of Raj's dog?", "Cinnamon", ["Pepper", "Ginger", "Nutmeg"], "hard"],
    ["What instrument can Leonard play?", "Cello", ["Violin", "Piano", "Flute"], "hard"],
    ["What is Sheldon's mother's name?", "Mary", ["Martha", "Margaret", "Maria"], "medium"],
    ["From which US state is Sheldon originally?", "Texas", ["Nebraska", "Ohio", "Georgia"], "medium"],
    ["What number does Sheldon claim is the best number?", "73", ["42", "7", "100"], "hard"],
    ["What game are the guys often seen playing on game night?", "Dungeons & Dragons", ["Monopoly", "Chess only", "Scrabble"], "medium"],
    ["What is the title Sheldon gives to his and Amy's web series?", "Fun with Flags", ["Flag Time", "Sheldon Cooper Presents", "Flag Facts"], "medium"],
    ["Who is Leonard's overbearing scientist mother?", "Beverly Hofstadter", ["Mary Cooper", "Susan", "Doris"], "hard"],
    ["What is Penny's eventual career after acting?", "Pharmaceutical sales rep", ["Teacher", "Chef", "Manager at the Cheesecake Factory"], "hard"],
    ["What does Sheldon insist on having on Saturdays?", "Laundry night routine", ["A movie marathon", "A hike", "A nap"], "medium"],
    ["What is Wil Wheaton's relationship to the show?", "He plays a fictionalized version of himself", ["He plays Sheldon's brother", "He plays a professor", "He plays Stuart"], "hard"],
    ["What is the name of Howard and Bernadette's daughter?", "Halley", ["Hayley", "Holly", "Hannah"], "hard"],
    ["What is Sheldon's favorite TV/franchise he adores?", "Star Trek", ["Star Wars only", "Doctor Who only", "Battlestar Galactica"], "medium"],
    ["What is the name of the apartment building's broken elevator running gag—what's wrong with it?", "It's out of order (broken)", ["It's too slow", "It's haunted", "It's too small"], "easy"],
    ["Which character has a peanut allergy?", "Howard", ["Leonard", "Raj", "Sheldon"], "medium"],
    ["Leonard is lactose intolerant—true or which trait is his?", "Lactose intolerant", ["Peanut allergy", "Gluten intolerant", "Nut allergy"], "medium"],
    ["What is Amy's nickname for Penny (they become best friends)?", "Bestie", ["Bff", "Pal", "Sis"], "medium"],
    ["What is the profession Sheldon's father had?", "He has passed away (was in oil/worked odd jobs)", ["A physicist", "A doctor", "A senator"], "hard"],
    ["Which actor plays Sheldon Cooper?", "Jim Parsons", ["Johnny Galecki", "Simon Helberg", "Kunal Nayyar"], "easy"],
    ["Which actor plays Leonard?", "Johnny Galecki", ["Jim Parsons", "Simon Helberg", "Kunal Nayyar"], "medium"],
    ["Which actress plays Penny?", "Kaley Cuoco", ["Mayim Bialik", "Melissa Rauch", "Kunal Nayyar"], "easy"],
    ["Which actress plays Amy?", "Mayim Bialik", ["Kaley Cuoco", "Melissa Rauch", "Sara Gilbert"], "medium"],
    ["What spin-off prequel series is about Sheldon's childhood?", "Young Sheldon", ["Little Sheldon", "Sheldon Begins", "Cooper Kids"], "easy"],
    ["What does Sheldon frequently correct people for confusing him with?", "Being told he's crazy ('I'm not crazy, my mother had me tested')", ["Being a doctor", "Being an engineer", "Being shy"], "medium"],
  ],
  "Taarak Mehta Ka Ooltah Chashmah": [
    ["What is the name of the society where the show is set?", "Gokuldham Society", ["Sahara Society", "Anand Nagar", "Shanti Niketan"], "easy"],
    ["What is the name of Jethalal's electronics shop?", "Gada Electronics", ["Gada Electricals", "Jetha Electronics", "Champak Electronics"], "easy"],
    ["What is the name of Jethalal's wife?", "Daya", ["Babita", "Madhavi", "Komal"], "easy"],
    ["What is the name of Jethalal's son?", "Tapu", ["Goli", "Pinku", "Gogi"], "easy"],
    ["What is the name of Jethalal's father?", "Champaklal", ["Nattu Kaka", "Bagha", "Bhide"], "easy"],
    ["What does Daya often exclaim?", "Hey Maa Mataji!", ["Hey Bhagwan!", "Oh Maa!", "Ram Ram!"], "easy"],
    ["By what affectionate name does Daya call Jethalal?", "Tapu ke papa", ["Jethiya", "Gada ji", "Pati dev"], "medium"],
    ["What is the full name of the society secretary, Bhide?", "Aatmaram Tukaram Bhide", ["Aatmaram Tukaram Bhinde", "Aatmaram Bhidewala", "Tukaram Aatmaram Bhide"], "medium"],
    ["What is the profession of Bhide?", "School teacher / tuition teacher", ["Doctor", "Lawyer", "Shopkeeper"], "easy"],
    ["What is the name of Bhide's wife?", "Madhavi", ["Daya", "Babita", "Roshan"], "medium"],
    ["What is the name of Bhide's daughter?", "Sonu", ["Sonia", "Sapna", "Simran"], "medium"],
    ["Jethalal has a not-so-secret crush on which neighbour?", "Babita ji", ["Madhavi", "Komal", "Roshan Kaur"], "easy"],
    ["Who is Babita's husband?", "Krishnan Iyer", ["Dr. Hathi", "Sodhi", "Popatlal"], "medium"],
    ["What is the profession of Krishnan Iyer?", "Scientist", ["Reporter", "Doctor", "Engineer"], "medium"],
    ["What is the profession of Popatlal?", "Reporter / journalist", ["Teacher", "Doctor", "Shopkeeper"], "easy"],
    ["What is the long-running gag about Popatlal?", "He is unmarried and desperate to find a bride", ["He is always sleeping", "He is very rich", "He owns the society"], "easy"],
    ["What is the name of the doctor in Gokuldham Society?", "Dr. Hansraj Hathi", ["Dr. Iyer", "Dr. Sodhi", "Dr. Bhide"], "medium"],
    ["What is Dr. Hathi famous for loving?", "Food (especially fafda-jalebi)", ["Cricket", "Singing", "Money"], "easy"],
    ["What is the name of Dr. Hathi's wife?", "Komal", ["Madhavi", "Babita", "Roshan"], "medium"],
    ["What is the name of Dr. Hathi's son?", "Goli (Gurucharan)", ["Pinku", "Gogi", "Tapu"], "medium"],
    ["What is the full name of the Punjabi member, Sodhi?", "Roshan Singh Sodhi", ["Roshan Singh Sandhu", "Hari Singh Sodhi", "Roshan Lal Sodhi"], "hard"],
    ["What is the name of Sodhi's wife?", "Roshan Kaur (Hawa Singh)", ["Madhavi", "Komal", "Babita"], "hard"],
    ["What are the names of Jethalal's two shop employees?", "Nattu Kaka and Bagha", ["Bagha and Goli", "Nattu Kaka and Tapu", "Abdul and Bagha"], "medium"],
    ["Who runs the small grocery shop below the society?", "Abdul", ["Nattu Kaka", "Bagha", "Sodhi"], "medium"],
    ["What is the name of the children's group led by Tapu?", "Tapu Sena", ["Tapu Gang", "Gokuldham Kids", "Bal Sena"], "easy"],
    ["On whose newspaper column is the show based?", "Taarak Mehta's 'Duniya Ne Undha Chashma'", ["R.K. Laxman's column", "A novel", "A film script"], "hard"],
    ["What is the profession of the character Taarak Mehta?", "Writer", ["Doctor", "Lawyer", "Reporter"], "medium"],
    ["What is the name of Taarak Mehta's wife?", "Anjali", ["Madhavi", "Daya", "Komal"], "hard"],
    ["What vehicle is Bhide most associated with?", "His scooter", ["A motorcycle", "A car", "A bicycle"], "medium"],
    ["Which two members have a constant comic rivalry (South Indian vs Marathi banter)?", "Iyer and Bhide", ["Jethalal and Sodhi", "Popatlal and Hathi", "Bagha and Nattu Kaka"], "medium"],
    ["What is Champaklal often called by Jethalal?", "Bapuji", ["Dada", "Babu", "Pita ji"], "easy"],
    ["Daya hails from which state (and loves to do Garba)?", "Gujarat", ["Punjab", "Maharashtra", "Rajasthan"], "medium"],
    ["What is the name of Daya's brother who often visits to borrow money?", "Sundar", ["Sukhram", "Suresh", "Sohan"], "hard"],
    ["Which festival celebrations are a recurring highlight in Gokuldham?", "All festivals together (Holi, Diwali, Navratri, etc.)", ["Only Diwali", "Only Holi", "No festivals"], "easy"],
    ["Who originally played Tapu in the early years?", "Bhavya Gandhi", ["Raj Anadkat", "Nidhi Bhanushali", "Samay Shah"], "hard"],
    ["Who is the longtime actor playing Jethalal?", "Dilip Joshi", ["Mandar Chandwadkar", "Shailesh Lodha", "Ghanshyam Nayak"], "medium"],
    ["Which actress is most associated with the role of Daya ben (left the show in 2017)?", "Disha Vakani", ["Munmun Dutta", "Sonalika Joshi", "Ambika Ranjankar"], "medium"],
    ["Who plays Babita ji?", "Munmun Dutta", ["Disha Vakani", "Sonalika Joshi", "Ambika Ranjankar"], "medium"],
    ["What is Bhide's first name often shortened to when scolding?", "Aatmaram", ["Tukaram", "Atmu", "Bhidu"], "hard"],
    ["What does Jethalal usually call Bhide in frustration?", "Bhide!", ["Master ji", "Secretary sahab", "Tukaram"], "easy"],
    ["What is the recurring profession-based gag for Popatlal's newspaper?", "He works for 'Toofan Express'", ["He owns a TV channel", "He runs a blog", "He is jobless"], "hard"],
    ["Which character is the society's secretary handling its affairs?", "Bhide", ["Jethalal", "Iyer", "Popatlal"], "easy"],
    ["What is the name of Sodhi and Roshan Kaur's son?", "Gogi", ["Goli", "Pinku", "Tapu"], "medium"],
    ["What does Jethalal frequently shout for his employee?", "Nattu Kaka!", ["Bagha!", "Tapu!", "Bhide!"], "easy"],
    ["What relation is Goli to Dr. Hathi?", "His son", ["His nephew", "His student", "His neighbour"], "easy"],
    ["What is the running joke about Bhide and money?", "He is very stingy/careful with money", ["He is extremely rich", "He gives loans freely", "He gambles"], "medium"],
    ["The Tapu Sena children belong to families in which society?", "Gokuldham", ["Sahara", "Anand Nagar", "Gokul Nagar"], "easy"],
    ["What kind of shop does Jethalal run (what does he sell)?", "Electronics (TVs, gadgets)", ["Groceries", "Clothes", "Sweets"], "easy"],
    ["Which member is a scientist always doing experiments?", "Iyer", ["Bhide", "Sodhi", "Popatlal"], "medium"],
    ["Who is the elderly father figure giving wisdom and old stories in the Gada house?", "Champaklal (Bapuji)", ["Nattu Kaka", "Bhide", "Iyer"], "easy"],
  ],
  "Bollywood Trivia": [
    ["\"Mogambo khush hua\" is an iconic dialogue from which film?", "Mr. India", ["Sholay", "Don", "Karma"], "medium"],
    ["\"Kitne aadmi the?\" is said by Gabbar Singh in which film?", "Sholay", ["Deewaar", "Don", "Zanjeer"], "easy"],
    ["Which film features the Oscar-winning song \"Jai Ho\"?", "Slumdog Millionaire", ["Lagaan", "Dil Se", "Taal"], "easy"],
    ["Who directed the film Lagaan?", "Ashutosh Gowariker", ["Karan Johar", "Sanjay Leela Bhansali", "Rajkumar Hirani"], "medium"],
    ["\"Bade bade deshon mein aisi choti choti baatein\" is from which film?", "Dilwale Dulhania Le Jayenge", ["Kuch Kuch Hota Hai", "Dil To Pagal Hai", "Mohabbatein"], "medium"],
    ["Which actor is nicknamed the 'He-Man' of Bollywood?", "Dharmendra", ["Amitabh Bachchan", "Vinod Khanna", "Jeetendra"], "hard"],
    ["\"Tareekh pe tareekh\" is a famous courtroom dialogue from which film?", "Damini", ["Andha Kanoon", "Meri Jung", "Kanoon"], "hard"],
    ["Shah Rukh Khan's production house is called?", "Red Chillies Entertainment", ["Dharma Productions", "Yash Raj Films", "Excel Entertainment"], "medium"],
    ["Which 1975 film is a legendary multi-starrer with Amitabh and Dharmendra?", "Sholay", ["Deewaar", "Don", "Trishul"], "easy"],
    ["Who composed the music for Slumdog Millionaire and Roja?", "A. R. Rahman", ["Pritam", "Shankar-Ehsaan-Loy", "Vishal-Shekhar"], "medium"],
    ["Which actor played the lead in '3 Idiots'?", "Aamir Khan", ["Shah Rukh Khan", "Salman Khan", "Hrithik Roshan"], "easy"],
    ["\"Don ko pakadna mushkil hi nahi, namumkin hai\" is from which film?", "Don", ["Deewaar", "Agneepath", "Kaalia"], "medium"],
    ["Aashiqui 2 (2013) was the breakthrough film of which actress?", "Shraddha Kapoor", ["Alia Bhatt", "Parineeti Chopra", "Kriti Sanon"], "medium"],
    ["Which Bollywood actor is known as 'Bhaijaan'?", "Salman Khan", ["Aamir Khan", "Shah Rukh Khan", "Saif Ali Khan"], "easy"],
    ["Who is often called the 'Badshah of Bollywood'?", "Shah Rukh Khan", ["Salman Khan", "Aamir Khan", "Akshay Kumar"], "easy"],
    ["Which film won India its first Academy Award nomination for Best Foreign Film (1957)?", "Mother India", ["Lagaan", "Salaam Bombay", "Awaara"], "hard"],
    ["Who directed Bajrangi Bhaijaan and Bajrangi's hit 'Bajrani'... i.e. directed Bajrangi Bhaijaan?", "Kabir Khan", ["Rajkumar Hirani", "Karan Johar", "Rohit Shetty"], "medium"],
    ["Which actress is nicknamed 'Dhak Dhak girl'?", "Madhuri Dixit", ["Sridevi", "Juhi Chawla", "Karisma Kapoor"], "hard"],
    ["Who directed the films PK and 3 Idiots?", "Rajkumar Hirani", ["Ashutosh Gowariker", "Karan Johar", "Imtiaz Ali"], "medium"],
    ["Which legendary actor starred in Mughal-e-Azam as Prince Salim?", "Dilip Kumar", ["Raj Kapoor", "Dev Anand", "Guru Dutt"], "hard"],
    ["The 'Karan Arjun' film starred Shah Rukh Khan and which other Khan?", "Salman Khan", ["Aamir Khan", "Saif Ali Khan", "Fardeen Khan"], "medium"],
    ["Which actor is known as 'Khiladi' of Bollywood?", "Akshay Kumar", ["Ajay Devgn", "Suniel Shetty", "Sunny Deol"], "medium"],
    ["Who played Munna Bhai in 'Munna Bhai M.B.B.S.'?", "Sanjay Dutt", ["Arshad Warsi", "Boman Irani", "Sunil Dutt"], "medium"],
    ["Who played Circuit in the Munna Bhai films?", "Arshad Warsi", ["Sanjay Dutt", "Johnny Lever", "Paresh Rawal"], "medium"],
    ["Which film features the dialogue \"Pushpa, I hate tears\"?", "Amar Prem", ["Aradhana", "Kati Patang", "Anand"], "hard"],
    ["Who directed the 2018 film 'Padmaavat'?", "Sanjay Leela Bhansali", ["Ashutosh Gowariker", "Karan Johar", "Rohit Shetty"], "medium"],
    ["Which actor delivered the dialogue \"Rishte mein toh hum tumhare baap lagte hain\"?", "Amitabh Bachchan", ["Shatrughan Sinha", "Dharmendra", "Vinod Khanna"], "hard"],
    ["Which film is it from: \"Mere paas maa hai\"?", "Deewaar", ["Sholay", "Trishul", "Zanjeer"], "medium"],
    ["Who is the 'Greek God' nicknamed actor known for dancing?", "Hrithik Roshan", ["Tiger Shroff", "Varun Dhawan", "Shahid Kapoor"], "medium"],
    ["Which director is known for action-comedies like the 'Golmaal' and 'Singham' series?", "Rohit Shetty", ["Karan Johar", "Anees Bazmee", "Sajid Khan"], "medium"],
    ["Who composed music as part of the trio 'Shankar-Ehsaan-Loy'? (name the trio's category)", "A music composer trio", ["A singing group", "A director duo", "A dance troupe"], "medium"],
    ["Which film launched Ranbir Kapoor as a lead actor (2007)?", "Saawariya", ["Wake Up Sid", "Rockstar", "Barfi!"], "hard"],
    ["Which actress won an Oscar-nominated film role... which actress starred in 'Queen' (2014)?", "Kangana Ranaut", ["Vidya Balan", "Anushka Sharma", "Sonam Kapoor"], "medium"],
    ["Who directed 'Gangs of Wasseypur'?", "Anurag Kashyap", ["Vishal Bhardwaj", "Imtiaz Ali", "Dibakar Banerjee"], "hard"],
    ["Which film features 'Kaun Banega Crorepati' host's acting comeback in 2000 with 'Mohabbatein'? Who is that host-actor?", "Amitabh Bachchan", ["Anil Kapoor", "Shah Rukh Khan", "Rishi Kapoor"], "medium"],
    ["Which actress is known as the 'first female superstar' of Hindi cinema, star of Mr. India and Chandni?", "Sridevi", ["Madhuri Dixit", "Rekha", "Hema Malini"], "hard"],
    ["Who played the title role in 'Bajirao Mastani' as Bajirao?", "Ranveer Singh", ["Ranbir Kapoor", "Hrithik Roshan", "Shahid Kapoor"], "medium"],
    ["Which 2016 film had Aamir Khan playing a wrestler-father?", "Dangal", ["Sultan", "Mary Kom", "Brothers"], "easy"],
    ["Who composed the famous song 'Tum Hi Ho' and which film is it from? (name the film)", "Aashiqui 2", ["Ek Villain", "Awarapan", "Hamari Adhuri Kahani"], "easy"],
    ["Which actor is known as 'Action King' / 'Garam Dharam'?", "Dharmendra", ["Sunny Deol", "Sanjay Dutt", "Mithun Chakraborty"], "hard"],
    ["Who directed the cult classic 'Andaz Apna Apna' (1994)?", "Rajkumar Santoshi", ["David Dhawan", "Priyadarshan", "Indra Kumar"], "hard"],
    ["Which film gave us the dialogue \"How's the josh?\"", "Uri: The Surgical Strike", ["Border", "LOC Kargil", "Lakshya"], "medium"],
    ["Who played Rancho in '3 Idiots'?", "Aamir Khan", ["R. Madhavan", "Sharman Joshi", "Boman Irani"], "easy"],
    ["Which veteran actress is called the 'Tragedy Queen' of Hindi cinema?", "Meena Kumari", ["Nargis", "Madhubala", "Waheeda Rehman"], "hard"],
    ["Which actor starred as the angry young man in 'Zanjeer' (1973)?", "Amitabh Bachchan", ["Vinod Khanna", "Shatrughan Sinha", "Dharmendra"], "medium"],
    ["Who directed 'Dilwale Dulhania Le Jayenge' (1995)?", "Aditya Chopra", ["Yash Chopra", "Karan Johar", "Sooraj Barjatya"], "medium"],
    ["Which film features the song 'Chaiyya Chaiyya' shot on a moving train?", "Dil Se", ["Taal", "Refugee", "Mission Kashmir"], "medium"],
    ["Who is known as the 'King of Romance' director, founder of Yash Raj Films?", "Yash Chopra", ["Aditya Chopra", "Karan Johar", "Subhash Ghai"], "medium"],
    ["Which actress made her debut with 'Student of the Year' (2012)?", "Alia Bhatt", ["Shraddha Kapoor", "Kriti Sanon", "Parineeti Chopra"], "medium"],
    ["Which 2001 film by Karan Johar starred SRK, Kajol, Amitabh, Hrithik and Kareena?", "Kabhi Khushi Kabhie Gham", ["Kal Ho Naa Ho", "Mohabbatein", "Kuch Kuch Hota Hai"], "easy"],
  ],
};

(async () => {
  await mongoose.connect(process.env.MONGO_URI);
  const names = Object.keys(SETS);
  await Question.deleteMany({ category: { $in: names } });
  let total = 0;
  for (const [category, items] of Object.entries(SETS)) {
    const docs = items.map(([q, a, wrong, level]) => {
      const opts = [a, ...wrong];
      for (let i = opts.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [opts[i], opts[j]] = [opts[j], opts[i]];
      }
      const cfg = LEVEL_CONFIG[level] || LEVEL_CONFIG.easy;
      return {
        category,
        question: q,
        options: opts,
        correctIndex: opts.indexOf(a),
        correctAnswer: a,
        mediaUrl: "",
        mediaType: "text",
        level,
        xpReward: cfg.xp,
        timeLimit: cfg.time,
      };
    });
    await Question.insertMany(docs);
    total += docs.length;
    console.log(`  ${category}: ${docs.length}`);
  }
  console.log(`\nSeeded ${total} questions across ${names.length} priority categories.`);
  await mongoose.disconnect();
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
