/**
 * Appends MORE curated questions to the hand-made categories (deduped by question
 * text, so it's safe to re-run / run alongside the base seeds).
 * Run: node scripts/seedCuratedExtra.js
 * Item format: [question, correctAnswer, [wrong1, wrong2, wrong3], level]
 */
require("dotenv").config();
const mongoose = require("mongoose");
const Question = require("../models/Question");
const LEVEL_CONFIG = { easy: { xp: 20, time: 12 }, medium: { xp: 40, time: 10 }, hard: { xp: 80, time: 8 } };

const SETS = {
  "The Office": [
    ["Who is the CFO of Dunder Mifflin that Michael reports to?", "David Wallace", ["Robert California", "Jan Levinson", "Ryan Howard"], "medium"],
    ["Where do Jim and Pam get married?", "Niagara Falls", ["Scranton", "New York City", "Las Vegas"], "medium"],
    ["What is the name of Jim and Pam's first child?", "Cece", ["Phillip", "Astrid", "Emma"], "medium"],
    ["What is Dwight's farmhand cousin's name?", "Mose", ["Zeke", "Jeb", "Heinrich"], "hard"],
    ["What does Andy Bernard call himself?", "The Nard Dog", ["Big Tuna", "The Andman", "Boss Bernard"], "medium"],
    ["Which Ivy League school does Andy constantly mention attending?", "Cornell", ["Yale", "Harvard", "Princeton"], "easy"],
    ["What is the name of Kevin's Police cover band?", "Scrantonicity", ["The Policemen", "Kevin and the Zits", "Cover Me"], "hard"],
    ["What animal is Angela obsessed with?", "Cats", ["Dogs", "Birds", "Rabbits"], "easy"],
    ["What is the name of Michael's annual office awards show?", "The Dundies", ["The Scrantons", "The Office Awards", "The Michaels"], "medium"],
    ["Which warehouse worker becomes a salesman and is the documentary's musician?", "Darryl", ["Roy", "Hide", "Glenn"], "medium"],
    ["Whom does Phyllis marry?", "Bob Vance", ["Bob Wallace", "Bob Kazamakis", "Bob Stanley"], "medium"],
    ["Bob Vance is always introduced with which company?", "Vance Refrigeration", ["Vance Plumbing", "Vance Paper", "Vance Logistics"], "medium"],
    ["With which branch does Scranton merge in season 3?", "Stamford", ["Utica", "Buffalo", "Nashua"], "medium"],
    ["Which company acquires Dunder Mifflin (the printer company)?", "Sabre", ["Staples", "Office Depot", "Prince Family Paper"], "medium"],
    ["Who is the eccentric CEO who replaces Michael's old boss, played by James Spader?", "Robert California", ["David Wallace", "Jo Bennett", "Gabe Lewis"], "hard"],
    ["Where does Michael move at the end of his time on the show?", "Colorado", ["Florida", "California", "Canada"], "medium"],
    ["Who is the HR representative Michael can't stand?", "Toby", ["Gabe", "Ryan", "Holly"], "easy"],
    ["Whom does Michael ultimately end up with?", "Holly Flax", ["Jan", "Pam", "Erin"], "medium"],
    ["What is Ryan's job title when the show begins?", "Temp", ["Salesman", "Accountant", "Manager"], "easy"],
    ["Who becomes the receptionist after Pam?", "Erin", ["Kelly", "Meredith", "Angela"], "medium"],
    ["What is the title of Michael's secret screenplay/movie?", "Threat Level Midnight", ["Agent Scarn", "Midnight Run", "The Scarn"], "medium"],
    ["What is the name of the hero Michael plays in his movie?", "Michael Scarn", ["Agent Michael", "Mike Danger", "Scott Scarn"], "hard"],
    ["What does Michael's coffee mug say?", "World's Best Boss", ["No. 1 Boss", "Boss Man", "King of Scranton"], "easy"],
    ["Which three employees make up the accounting department?", "Oscar, Angela and Kevin", ["Oscar, Kevin and Toby", "Angela, Kevin and Ryan", "Oscar, Angela and Creed"], "medium"],
    ["What is the name of Stanley's favorite work holiday?", "Pretzel Day", ["Casual Friday", "Bonus Day", "Cookie Day"], "medium"],
    ["What was the name of Pam's high-school sweetheart / fiancé at the start?", "Roy", ["Jim", "Mark", "Brian"], "easy"],
    ["Who becomes regional manager of the Scranton branch in the finale?", "Dwight", ["Jim", "Andy", "Kevin"], "medium"],
    ["Who is Dwight's best man at his wedding?", "Michael", ["Jim", "Mose", "Andy"], "hard"],
    ["What martial-art/role does Dwight proudly volunteer for?", "Sheriff's deputy", ["Firefighter", "Paramedic", "Soldier"], "hard"],
    ["At which event do Jim and Pam first kiss?", "Casino Night", ["The Dundies", "Beach Day", "The office party"], "medium"],
    ["What does Jim do with Dwight's stapler besides Jell-O (puts it in)...?", "Encases his items in Jell-O", ["Hides them in the ceiling", "Throws them out", "Sells them"], "easy"],
    ["What city is the show set in?", "Scranton, Pennsylvania", ["Stamford, Connecticut", "Buffalo, New York", "Akron, Ohio"], "easy"],
    ["What format is The Office filmed in?", "A mockumentary", ["A sitcom with a laugh track", "A soap opera", "An animated series"], "easy"],
    ["Who is Kelly Kapoor's on-again, off-again boyfriend?", "Ryan", ["Darryl", "Andy", "Gabe"], "medium"],
    ["What dance move does Michael Scarn perform?", "The Scarn", ["The Worm", "The Robot", "The Scranton Shuffle"], "hard"],
  ],
  "Modern Family": [
    ["Who is the patriarch connecting all three families?", "Jay Pritchett", ["Phil Dunphy", "Mitchell", "Frank"], "easy"],
    ["Who is Phil Dunphy's wife?", "Claire", ["Gloria", "Haley", "DeDe"], "easy"],
    ["Who is Mitchell's partner/husband?", "Cameron (Cam)", ["Manny", "Jay", "Gil"], "easy"],
    ["From which US state and background is Cameron?", "A Missouri farm", ["A Texas ranch", "A New York suburb", "A California beach"], "medium"],
    ["What was Cam's job at the local high school?", "Music teacher / football coach", ["Principal", "Janitor", "Science teacher"], "hard"],
    ["Who is Haley's long-term boyfriend and eventual husband?", "Dylan", ["Andy", "Arvin", "Rainer"], "medium"],
    ["What country was Lily adopted from?", "Vietnam", ["China", "Colombia", "South Korea"], "medium"],
    ["Who is Manny's biological father?", "Javier", ["Jay", "Phil", "Gil"], "medium"],
    ["What is the name of Jay and DeDe's daughter?", "Claire", ["Gloria", "Haley", "Pameron"], "medium"],
    ["Who is Jay's ex-wife and mother of Claire and Mitchell?", "DeDe", ["Gloria", "Barb", "Pam"], "hard"],
    ["What is the name of Cam's sister?", "Pameron", ["Pam", "Patricia", "Paula"], "hard"],
    ["Which college does Alex attend?", "Caltech", ["MIT", "Stanford", "Harvard"], "medium"],
    ["What business does Claire eventually take over from Jay?", "The closet company", ["A restaurant", "A car dealership", "A law firm"], "medium"],
    ["Which war is Jay a veteran of?", "The Vietnam War", ["The Korean War", "World War II", "The Gulf War"], "hard"],
    ["What is the name of Jay's business rival realtor who taunts Phil?", "Gil Thorpe", ["Earl Chambers", "Tad", "Marty"], "hard"],
    ["What hobby/skill is Phil passionate about (magic and ...)?", "Magic and cheerleading", ["Cooking", "Boxing", "Painting"], "medium"],
    ["What is Manny known for being (his personality)?", "Sophisticated/old soul, into poetry and cooking", ["A jock", "A prankster", "A slacker"], "medium"],
    ["Which Dunphy child is the underachiever/goofball?", "Luke", ["Alex", "Haley", "Manny"], "easy"],
    ["Who is the youngest child of Jay and Gloria?", "Joe", ["Manny", "Fulgencio", "Dylan"], "easy"],
    ["What are the names of Haley and Dylan's twins?", "Poppy and George", ["Jack and Erica", "Lily and Joe", "Calhoun and Poppy"], "hard"],
    ["What is Mitchell's profession for most of the series?", "Lawyer", ["Accountant", "Architect", "Teacher"], "easy"],
    ["Gloria is originally from which country?", "Colombia", ["Mexico", "Venezuela", "Cuba"], "easy"],
    ["What is the name of Jay's dog?", "Stella", ["Larry", "Bruno", "Daisy"], "medium"],
    ["What is the name of the cat in the Pritchett household (Mitchell once had)?", "Larry", ["Stella", "Whiskers", "Felix"], "hard"],
    ["What is Phil's self-described parenting persona?", "The cool dad", ["The strict dad", "The absent dad", "The funny uncle"], "easy"],
    ["What instrument/activity is Dylan known for (he's in a band)?", "Music (he sings/plays guitar)", ["Painting", "Skating", "Cooking"], "medium"],
    ["What is the title of Phil's book of life rules?", "Phil's-osophy", ["Phil's Rules", "Cool Dad's Guide", "Dunphy Wisdom"], "easy"],
    ["What is Cam's flamboyant clown alter ego?", "Fizbo", ["Bozo", "Pippo", "Chuckles"], "medium"],
    ["Who narrates/centers the families (whose remarriage starts the show)?", "Jay (marrying Gloria)", ["Phil", "Mitchell", "Claire"], "medium"],
    ["What kind of lawyer does Mitchell become later (environmental focus)?", "Environmental lawyer", ["Criminal lawyer", "Divorce lawyer", "Corporate lawyer"], "hard"],
    ["What is Gloria famous for (comedic trait with English)?", "Mispronouncing English words/phrases", ["Speaking five languages", "Never speaking", "Being mute"], "easy"],
    ["Which child is the eldest Dunphy?", "Haley", ["Alex", "Luke", "Manny"], "easy"],
    ["What is the full company name of Jay's business?", "Pritchett's Closets & Blinds", ["Pritchett Realty", "Jay's Closets", "Closet Kings"], "hard"],
    ["What is Manny's relationship to Jay?", "Stepson (Gloria's son)", ["Son", "Nephew", "Grandson"], "easy"],
  ],
  "Harry Potter": [
    ["What is the Hogwarts school motto (translated)?", "Never tickle a sleeping dragon", ["Knowledge is power", "Magic above all", "Fear the dark"], "hard"],
    ["How many points is catching the Golden Snitch worth?", "150", ["100", "50", "200"], "medium"],
    ["How many goal hoops does each Quidditch team defend?", "Three", ["Two", "Four", "One"], "medium"],
    ["What guards the entrance to the Gryffindor common room?", "The Fat Lady portrait", ["A suit of armor", "A talking gargoyle", "A riddle"], "medium"],
    ["To enter the Ravenclaw common room you must?", "Answer a riddle", ["Say a password", "Tap a brick", "Bow to a portrait"], "hard"],
    ["What was Harry's first broomstick?", "Nimbus 2000", ["Firebolt", "Comet 260", "Cleansweep Seven"], "medium"],
    ["Who gives Harry a Firebolt broom?", "Sirius Black", ["Dumbledore", "Hagrid", "Lupin"], "medium"],
    ["What is the emergency transport for stranded witches and wizards?", "The Knight Bus", ["The Hogwarts Express", "Floo Network", "Thestrals"], "medium"],
    ["What powder lets wizards travel through fireplaces?", "Floo powder", ["Apparition dust", "Portkey ash", "Smoke salt"], "medium"],
    ["What is the dangerous side-effect of failed Apparition?", "Splinching", ["Fainting", "Burning", "Memory loss"], "hard"],
    ["What is the wizarding newspaper?", "The Daily Prophet", ["The Quibbler", "Witch Weekly", "The Oracle"], "medium"],
    ["Who publishes The Quibbler magazine?", "Xenophilius Lovegood", ["Rita Skeeter", "Barnabas Cuffe", "Bathilda Bagshot"], "hard"],
    ["Which house is Luna Lovegood in?", "Ravenclaw", ["Gryffindor", "Hufflepuff", "Slytherin"], "medium"],
    ["Who is Harry's first kiss?", "Cho Chang", ["Ginny", "Hermione", "Lavender"], "medium"],
    ["What type of owl is Hedwig?", "A snowy owl", ["A barn owl", "A tawny owl", "An eagle owl"], "easy"],
    ["What is the name of the Weasley family's owl?", "Errol", ["Hermes", "Pigwidgeon", "Hedwig"], "hard"],
    ["What is the core of Voldemort's wand?", "A phoenix feather (from Fawkes)", ["A dragon heartstring", "A unicorn hair", "A basilisk fang"], "medium"],
    ["What effect occurs when Harry's and Voldemort's wands meet?", "Priori Incantatem", ["Avada Kedavra", "Expelliarmus", "Fidelius"], "hard"],
    ["Who are 'R.A.B.', the initials in the fake locket?", "Regulus Arcturus Black", ["Rabastan Black", "Rodolphus Black", "Regulus Aldous Black"], "hard"],
    ["Where was Helga Hufflepuff's cup Horcrux kept?", "In Bellatrix's Gringotts vault", ["At Hogwarts", "In a cave", "At Malfoy Manor"], "hard"],
    ["Which Horcrux was hidden in the Room of Requirement?", "Ravenclaw's diadem", ["The locket", "The cup", "The ring"], "hard"],
    ["What deadly fire does Crabbe unleash, destroying the diadem?", "Fiendfyre", ["Incendio", "Bluebell flames", "Confringo"], "hard"],
    ["Who tortured Neville's parents into insanity?", "Bellatrix Lestrange", ["Lucius Malfoy", "Greyback", "Barty Crouch Sr"], "medium"],
    ["What is the name of the wizarding hospital?", "St Mungo's", ["Azkaban", "Nurmengard", "Mungo's Cross"], "medium"],
    ["What is the name of Neville's pet toad?", "Trevor", ["Scabbers", "Crookshanks", "Nibbles"], "medium"],
    ["What is the name of Hagrid's baby dragon?", "Norbert(a)", ["Norberta only", "Fluffy", "Buckbeak"], "medium"],
    ["Who is Hagrid's giant half-brother?", "Grawp", ["Golgomath", "Karkus", "Fridwulfa"], "hard"],
    ["Who is the Hogwarts flying instructor?", "Madam Hooch", ["Madam Pomfrey", "Professor Sprout", "Madam Pince"], "medium"],
    ["Who is the Hogwarts matron/nurse?", "Madam Pomfrey", ["Madam Hooch", "Madam Pince", "Professor Sprout"], "medium"],
    ["Who teaches Herbology and heads Hufflepuff House?", "Professor Sprout", ["Professor McGonagall", "Madam Hooch", "Professor Trelawney"], "medium"],
    ["Who teaches Charms and heads Ravenclaw House?", "Professor Flitwick", ["Professor Binns", "Professor Slughorn", "Professor Sprout"], "medium"],
    ["Which ghost teaches History of Magic?", "Professor Binns", ["Nearly Headless Nick", "The Bloody Baron", "Professor Flitwick"], "hard"],
    ["What do the exams 'O.W.L.s' stand for?", "Ordinary Wizarding Levels", ["Official Wizard Licences", "Ordinary Witch Lessons", "Outstanding Wizard Levels"], "hard"],
    ["What do 'N.E.W.T.s' stand for?", "Nastily Exhausting Wizarding Tests", ["New Examined Wizard Trials", "Notable Exams for Wizard Training", "Necessary Exams for Wizards"], "hard"],
    ["Into the graveyard, the Triwizard Cup turns out to be a?", "Portkey", ["Trophy only", "Time-Turner", "Decoy"], "medium"],
    ["What three ingredients revive Voldemort's body?", "Bone of the father, flesh of the servant, blood of the enemy", ["Hair, blood and tears", "Unicorn blood and venom", "Three Horcruxes"], "hard"],
    ["What is Albus Dumbledore's full first-to-last name set?", "Albus Percival Wulfric Brian Dumbledore", ["Albus Brian Wulfric Dumbledore", "Albus Wulfric Percival Dumbledore", "Albus Brian Percival Dumbledore"], "hard"],
    ["Who is Dumbledore's brother who runs the Hog's Head?", "Aberforth", ["Aberforth's son", "Gellert", "Elphias"], "hard"],
    ["In what year did Dumbledore defeat the dark wizard Grindelwald?", "1945", ["1926", "1981", "1899"], "hard"],
    ["What house do the Patil twins... which house is Parvati Patil in?", "Gryffindor", ["Ravenclaw", "Hufflepuff", "Slytherin"], "hard"],
    ["What is the name of the impostor who teaches Defence in Goblet of Fire?", "Barty Crouch Jr (as Mad-Eye Moody)", ["The real Mad-Eye Moody", "Igor Karkaroff", "Peter Pettigrew"], "hard"],
    ["What unusual feature is Mad-Eye Moody famous for?", "A magical revolving eye", ["A wooden wand-arm", "A scarred face only", "A talking hat"], "medium"],
    ["Who is the centaur that briefly teaches Divination?", "Firenze", ["Bane", "Magorian", "Ronan"], "hard"],
    ["What is the name of the three Peverell brothers' legend tied to the Hallows?", "The Tale of the Three Brothers", ["The Deathly Tale", "The Hallow Legend", "The Wand Maker's Tale"], "medium"],
    ["Whose murder makes Snape the true master of the Elder Wand (before Draco disarms Dumbledore)... who actually disarmed Dumbledore?", "Draco Malfoy", ["Snape", "Voldemort", "Harry"], "hard"],
    ["What does Harry do with the Elder Wand after defeating Voldemort?", "Uses it to repair his own wand, then returns it", ["Keeps it", "Snaps it immediately", "Gives it to Hermione"], "hard"],
    ["What is the name of the Black family house-elf who serves at Grimmauld Place?", "Kreacher", ["Dobby", "Winky", "Hokey"], "medium"],
    ["Which house-elf is freed and works at Hogwarts kitchens with Dobby?", "Winky", ["Kreacher", "Hokey", "Nagini"], "hard"],
  ],
  Friends: [
    ["What is the name of Ross's second wife?", "Emily", ["Carol", "Julie", "Mona"], "medium"],
    ["What nationality is Ross's second wife Emily?", "British", ["French", "American", "Italian"], "medium"],
    ["Whose name does Ross say at the altar instead of Emily's?", "Rachel", ["Carol", "Monica", "Susan"], "easy"],
    ["What is the name of Ross's ex-wife who is a lesbian?", "Carol", ["Emily", "Susan", "Julie"], "medium"],
    ["Who is Carol's partner?", "Susan", ["Sophie", "Kate", "Sarah"], "medium"],
    ["What is the profession of Rachel's father, Dr. Green?", "A doctor", ["A lawyer", "A banker", "A professor"], "hard"],
    ["What is the name of the smoking-hot dance Monica dated/ the high-school friend... what was Monica's weight-related flashback nickname?", "Fat Monica", ["Big Mon", "Chunky Monica", "Mon-Mon"], "medium"],
    ["What is Joey's twin-like roommate game they play with a foosball table—what do Joey and Chandler love playing?", "Foosball", ["Ping pong", "Darts", "Pool"], "medium"],
    ["What is the name of Phoebe's birth mother?", "Phoebe Abbott", ["Lily Buffay", "Frances", "Ursula"], "hard"],
    ["What instrument-based career did Ross pursue in his youth (he played in a band)?", "Keyboard (he made experimental 'music')", ["Drums", "Guitar", "Trumpet"], "hard"],
    ["Who plays Rachel's sister Jill?", "Reese Witherspoon", ["Christina Applegate", "Winona Ryder", "Brooke Shields"], "hard"],
    ["Who plays Rachel's sister Amy?", "Christina Applegate", ["Reese Witherspoon", "Sela Ward", "Kristin Davis"], "hard"],
    ["What is the name of Monica and Ross's grandmother whose recipe is involved... what is the famous cookie recipe Phoebe seeks?", "Nestlé Toll House", ["Grandma's Secret", "Buffay Special", "Betty Crocker"], "hard"],
    ["What is Gunther secretly in love with?", "Rachel", ["Phoebe", "Monica", "Janice"], "easy"],
    ["What is the name of the woman Chandler is in a relationship with before Monica (with the annoying laugh/voice)?", "Janice", ["Kathy", "Aurora", "Joanna"], "medium"],
    ["What does Ross train to become an expert in (a martial term he made up)?", "Unagi (a state of total awareness)", ["Karate", "Jiu-jitsu", "Tai chi"], "medium"],
    ["Which friend has a fear of dogs?", "Chandler", ["Ross", "Joey", "Phoebe"], "medium"],
    ["Who officiates the wedding of Monica and Chandler?", "Joey", ["Ross", "Gunther", "Mr. Geller"], "medium"],
    ["Whom does Phoebe date that is played by Bruce Willis (her boyfriend's father)?", "Paul", ["Mike", "David", "Gary"], "hard"],
    ["What musician boyfriend (a scientist) does Phoebe almost stay with before Mike—what's the name of David the scientist's destination?", "Minsk", ["Moscow", "Prague", "Kiev"], "hard"],
    ["What is the name of Joey's hand twin / he finds someone with identical hands at a casino?", "Hand twin", ["Palm pal", "Mirror man", "Twin grip"], "hard"],
    ["What does Rachel name the baby (and from whom did she 'take' the name)?", "Emma (Monica's pick)", ["Ella", "Emily", "Erica"], "medium"],
  ],
  "The Big Bang Theory": [
    ["What is the name of Leonard's domineering scientist mother?", "Beverly Hofstadter", ["Mary Cooper", "Susan", "Doris"], "hard"],
    ["What is Raj's surname?", "Koothrappali", ["Patel", "Nair", "Kapoor"], "medium"],
    ["What is the name of Raj's dog?", "Cinnamon", ["Ginger", "Pepper", "Nutmeg"], "hard"],
    ["What number is Sheldon's favorite?", "73", ["42", "7", "100"], "hard"],
    ["What is Howard and Bernadette's daughter named?", "Halley", ["Hayley", "Holly", "Hannah"], "hard"],
    ["What is the title of Sheldon and Amy's web series?", "Fun with Flags", ["Flag Time", "Sheldon Says", "Flag Facts"], "medium"],
    ["From which US state does Sheldon hail?", "Texas", ["Nebraska", "Ohio", "Georgia"], "medium"],
    ["What is Bernadette's profession?", "Microbiologist", ["Teacher", "Nurse", "Engineer"], "medium"],
    ["What instrument can Leonard play?", "Cello", ["Violin", "Piano", "Flute"], "hard"],
    ["What allergy does Howard have?", "Peanut allergy", ["Bee sting allergy only", "Gluten", "Dairy"], "medium"],
    ["What condition makes Leonard avoid dairy?", "Lactose intolerance", ["A peanut allergy", "Gluten intolerance", "A nut allergy"], "medium"],
    ["Which prize do Sheldon and Amy jointly win?", "The Nobel Prize in Physics", ["The Fields Medal", "The Turing Award", "A MacArthur grant"], "hard"],
    ["Who plays a fictionalized version of himself and feuds with Sheldon?", "Wil Wheaton", ["George Takei", "LeVar Burton", "Brent Spiner"], "hard"],
    ["What is Sheldon's mother's first name?", "Mary", ["Martha", "Margaret", "Maria"], "medium"],
    ["What is the prequel series about Sheldon's childhood called?", "Young Sheldon", ["Little Sheldon", "Sheldon Begins", "Cooper Kids"], "easy"],
    ["What game do the guys play on game night involving dice and dungeons?", "Dungeons & Dragons", ["Settlers of Catan only", "Risk", "Clue"], "medium"],
    ["Which actor plays Sheldon Cooper?", "Jim Parsons", ["Johnny Galecki", "Simon Helberg", "Kunal Nayyar"], "easy"],
    ["Which actress plays Penny?", "Kaley Cuoco", ["Mayim Bialik", "Melissa Rauch", "Sara Gilbert"], "easy"],
    ["What franchise is Sheldon most devoted to?", "Star Trek", ["Star Wars", "Doctor Who", "Battlestar Galactica"], "medium"],
    ["What is the name of the comic book store owner who is often lonely?", "Stuart", ["Steve", "Stan", "Simon"], "medium"],
    ["What does Sheldon demand everyone sign to live or date within the group?", "An agreement (Roommate/Relationship Agreement)", ["A waiver", "A contract for rent only", "Nothing"], "easy"],
    ["What is Penny's career after she stops waitressing/acting?", "Pharmaceutical sales representative", ["Teacher", "Chef", "Director"], "hard"],
  ],
  "Taarak Mehta Ka Ooltah Chashmah": [
    ["Who plays the role of Jethalal?", "Dilip Joshi", ["Shailesh Lodha", "Mandar Chandwadkar", "Ghanshyam Nayak"], "medium"],
    ["Which actor played the original Taarak Mehta for many years?", "Shailesh Lodha", ["Dilip Joshi", "Mandar Chandwadkar", "Sachin Shroff"], "hard"],
    ["What is the name of the lane where Gokuldham Society is located?", "Powder Gali", ["Hira Gali", "Gokul Road", "Champak Marg"], "hard"],
    ["What is Nattu Kaka's role at Gada Electronics?", "Shop assistant/employee", ["Manager", "Owner", "Accountant"], "easy"],
    ["What is Bagha's relationship to Nattu Kaka in the show?", "His nephew (and co-worker)", ["His brother", "His son", "His friend only"], "hard"],
    ["What is the recurring crush gag involving Jethalal and Babita?", "Jethalal is smitten with Babita ji", ["They are siblings", "They are business partners", "They are enemies"], "easy"],
    ["What sweet/snack is Dr. Hathi most associated with craving?", "Fafda-jalebi", ["Samosa", "Gulab jamun", "Vada pav"], "medium"],
    ["What does Champaklal often share with everyone?", "Old stories and wisdom", ["Money", "Sweets only", "Songs"], "easy"],
    ["Which member of the society is a newspaper reporter?", "Popatlal", ["Iyer", "Bhide", "Sodhi"], "easy"],
    ["What is the running joke about Popatlal's marriage?", "He keeps failing to find a bride", ["He is secretly married", "He hates marriage", "He married twice"], "easy"],
    ["What is Iyer's profession?", "Scientist", ["Doctor", "Teacher", "Reporter"], "medium"],
    ["Who is Iyer's wife?", "Babita", ["Madhavi", "Komal", "Daya"], "easy"],
    ["What does Bhide do for extra income besides being secretary?", "Runs tuition classes", ["Drives a taxi", "Sells vegetables", "Repairs TVs"], "medium"],
    ["What is the name of Bhide and Madhavi's daughter?", "Sonu", ["Sonia", "Sneha", "Sapna"], "medium"],
    ["Which child group does Tapu lead?", "Tapu Sena", ["Bal Sena", "Gokul Gang", "Dhamaal Sena"], "easy"],
    ["Who originally portrayed Tapu before being replaced?", "Bhavya Gandhi", ["Raj Anadkat", "Samay Shah", "Nidhi Bhanushali"], "hard"],
    ["What state's culture/dance (Garba) is Daya associated with?", "Gujarat", ["Punjab", "Maharashtra", "Rajasthan"], "medium"],
    ["What is Sodhi's profession/community trait?", "He is a Punjabi member of the society", ["A South Indian scientist", "A Gujarati businessman", "A Bengali doctor"], "medium"],
    ["Who is the doctor of Gokuldham Society?", "Dr. Hansraj Hathi", ["Dr. Iyer", "Dr. Sodhi", "Dr. Bhide"], "easy"],
    ["What is Dr. Hathi's son's name?", "Goli", ["Gogi", "Pinku", "Tapu"], "medium"],
    ["Who runs the small shop below Gokuldham Society?", "Abdul", ["Nattu Kaka", "Sodhi", "Bagha"], "medium"],
    ["What is the relationship between Jethalal and Champaklal?", "Father and son (Champaklal is the father)", ["Brothers", "Uncle and nephew", "Friends"], "easy"],
  ],
  "Bollywood Trivia": [
    ["Who directed 'Sholay' (1975)?", "Ramesh Sippy", ["Yash Chopra", "Manmohan Desai", "Prakash Mehra"], "hard"],
    ["Which actor is known as the 'Shahenshah' of Bollywood?", "Amitabh Bachchan", ["Dilip Kumar", "Rajesh Khanna", "Dharmendra"], "easy"],
    ["Who was Bollywood's first 'superstar', star of Aradhana and Anand?", "Rajesh Khanna", ["Amitabh Bachchan", "Dev Anand", "Shammi Kapoor"], "hard"],
    ["Which film won the National Award and made Aamir Khan a wrestling coach?", "Dangal", ["Sultan", "Mary Kom", "Chak De! India"], "easy"],
    ["Who played the female lead opposite SRK in 'Dilwale Dulhania Le Jayenge'?", "Kajol", ["Madhuri Dixit", "Karisma Kapoor", "Juhi Chawla"], "easy"],
    ["Which film features the character 'Vijay Dinanath Chauhan'?", "Agneepath", ["Deewaar", "Zanjeer", "Shakti"], "medium"],
    ["Who directed 'Mughal-e-Azam' (1960)?", "K. Asif", ["Mehboob Khan", "Bimal Roy", "Guru Dutt"], "hard"],
    ["Which actress is known as 'Mads' / the 'Dhak Dhak' girl?", "Madhuri Dixit", ["Sridevi", "Juhi Chawla", "Raveena Tandon"], "medium"],
    ["Which 2013 film featured Deepika and Ranveer in a Gujarati Romeo-Juliet tale?", "Goliyon Ki Raasleela Ram-Leela", ["Bajirao Mastani", "Padmaavat", "Lootera"], "medium"],
    ["Who directed 'PK' and 'Munna Bhai M.B.B.S.'?", "Rajkumar Hirani", ["Anurag Kashyap", "Imtiaz Ali", "Karan Johar"], "medium"],
    ["Which actor is nicknamed 'King Khan'?", "Shah Rukh Khan", ["Salman Khan", "Aamir Khan", "Saif Ali Khan"], "easy"],
    ["Who composed the iconic background music and is known for 'Mozart of Madras'?", "A. R. Rahman", ["R. D. Burman", "Pritam", "Ilaiyaraaja"], "medium"],
    ["Which film gave the dialogue 'All is well'?", "3 Idiots", ["PK", "Munna Bhai M.B.B.S.", "Taare Zameen Par"], "easy"],
    ["Which veteran composer is fondly called 'Pancham Da'?", "R. D. Burman", ["S. D. Burman", "Naushad", "Madan Mohan"], "hard"],
    ["Who directed 'Lagaan' and 'Jodhaa Akbar'?", "Ashutosh Gowariker", ["Sanjay Leela Bhansali", "Karan Johar", "Rakeysh Mehra"], "medium"],
    ["Which film features 'Gabbar Singh' as the villain?", "Sholay", ["Don", "Deewaar", "Sholay 2"], "easy"],
    ["Who played the role of Phunsukh Wangdu/Rancho in 3 Idiots?", "Aamir Khan", ["Sharman Joshi", "R. Madhavan", "Boman Irani"], "easy"],
    ["Which actress made her debut in 'Raazi' as a... no — who starred as a spy in 'Raazi' (2018)?", "Alia Bhatt", ["Deepika Padukone", "Kangana Ranaut", "Anushka Sharma"], "medium"],
    ["Who directed the Dhoom film franchise's first installment (2004)?", "Sanjay Gadhvi", ["Rohit Shetty", "Farhan Akhtar", "Kabir Khan"], "hard"],
    ["Which actor is referred to as 'Bhaijaan' by fans?", "Salman Khan", ["Aamir Khan", "Shah Rukh Khan", "Sunny Deol"], "easy"],
    ["Which film is famous for the dialogue 'Picture abhi baaki hai mere dost'?", "Om Shanti Om", ["Don", "Main Hoon Na", "Happy New Year"], "medium"],
    ["Who directed 'Gully Boy' (2019)?", "Zoya Akhtar", ["Farhan Akhtar", "Reema Kagti", "Anurag Kashyap"], "medium"],
  ],
  "Bollywood Music": [
    ["Who sang the iconic 'Mere Sapno Ki Rani'?", "Kishore Kumar", ["Mohammed Rafi", "Mukesh", "Manna Dey"], "medium"],
    ["'Tujhe Dekha To' from DDLJ was sung by Lata Mangeshkar and which male singer?", "Kumar Sanu", ["Udit Narayan", "Sonu Nigam", "Abhijeet"], "hard"],
    ["Who sang 'Pehla Nasha' from Jo Jeeta Wohi Sikandar?", "Udit Narayan and Sadhana Sargam", ["Kumar Sanu and Alka Yagnik", "Sonu Nigam and Shreya Ghoshal", "Mohammed Aziz and Asha"], "hard"],
    ["'Kal Ho Naa Ho' title track was sung by?", "Sonu Nigam", ["Shaan", "Udit Narayan", "KK"], "medium"],
    ["Who sang 'Tum Hi Ho' from Aashiqui 2?", "Arijit Singh", ["Atif Aslam", "Mohit Chauhan", "Ankit Tiwari"], "easy"],
    ["The song 'Malhari' is from which film?", "Bajirao Mastani", ["Padmaavat", "Ram-Leela", "Tanhaji"], "medium"],
    ["Who composed the music of 'Rockstar'?", "A. R. Rahman", ["Pritam", "Amit Trivedi", "Vishal-Shekhar"], "medium"],
    ["'Channa Mereya' is from which film?", "Ae Dil Hai Mushkil", ["Ok Jaanu", "Tamasha", "Rockstar"], "medium"],
    ["Who is known as the 'Melody Queen' of Indian playback?", "Lata Mangeshkar", ["Asha Bhosle", "Geeta Dutt", "Shamshad Begum"], "easy"],
    ["'Senorita' from Zindagi Na Milegi Dobara was sung by the three lead actors and which composer trio?", "Shankar-Ehsaan-Loy", ["Vishal-Shekhar", "Salim-Sulaiman", "Sajid-Wajid"], "hard"],
    ["Which singer is famous for 'Chaiyya Chaiyya' and 'Dard-e-Disco'?", "Sukhwinder Singh", ["Sonu Nigam", "Kailash Kher", "Mika Singh"], "hard"],
    ["'Galliyan' (Teri Galliyan) is from which film?", "Ek Villain", ["Aashiqui 2", "Hero", "Half Girlfriend"], "medium"],
    ["Who sang and composed 'Kun Faya Kun'?", "A. R. Rahman (with Javed Ali & Mohit Chauhan)", ["Pritam", "Amit Trivedi", "Sonu Nigam"], "hard"],
    ["'Gerua' from Dilwale was primarily sung by?", "Arijit Singh", ["Atif Aslam", "Armaan Malik", "Jubin Nautiyal"], "medium"],
    ["Which legendary singer-actor is known as 'Bollywood's first playback superstar', also a comedian-singer?", "Kishore Kumar", ["Mohammed Rafi", "Mukesh", "Talat Mahmood"], "medium"],
    ["'Jai Ho' from Slumdog Millionaire was composed by?", "A. R. Rahman", ["Pritam", "Shankar-Ehsaan-Loy", "Vishal-Shekhar"], "easy"],
    ["Which female singer is the daughter of a famous music director and sang 'Teri Ore'?", "Shreya Ghoshal", ["Sunidhi Chauhan", "Neha Kakkar", "Palak Muchhal"], "hard"],
    ["'Apna Time Aayega' from Gully Boy is performed by?", "Ranveer Singh (with DIVINE)", ["Badshah", "Yo Yo Honey Singh", "Raftaar"], "medium"],
    ["Who composed the music for most of 'Ae Dil Hai Mushkil' and 'Barfi!'?", "Pritam", ["A. R. Rahman", "Amit Trivedi", "Vishal-Shekhar"], "medium"],
    ["'Agar Tum Saath Ho' from Tamasha was sung by Alka Yagnik and?", "Arijit Singh", ["Mohit Chauhan", "Atif Aslam", "Papon"], "hard"],
  ],
  "Bollywood Name Puzzles": [
    ["Complete the actor's name: Ranveer ___", "Singh", ["Kapoor", "Khan", "Shroff"], "easy"],
    ["Complete the actress's name: Kareena ___", "Kapoor", ["Khan", "Padukone", "Sharma"], "easy"],
    ["Complete the actor's name: Tiger ___", "Shroff", ["Singh", "Kapoor", "Khan"], "easy"],
    ["Complete the actress's name: Katrina ___", "Kaif", ["Kapoor", "Kaur", "Khan"], "easy"],
    ["Complete the film title: Kuch Kuch Hota ___", "Hai", ["Tha", "Raha", "Jaye"], "easy"],
    ["Complete the film title: Dil Chahta ___", "Hai", ["Tha", "Hoga", "Raha"], "easy"],
    ["Complete the film title: Kabhi Alvida Naa ___", "Kehna", ["Bolna", "Jaana", "Sochna"], "medium"],
    ["Complete the film title: Hum Aapke Hain ___", "Koun..!", ["Yaar", "Sang", "Dost"], "medium"],
    ["Complete the film title: Jab Tak Hai ___", "Jaan", ["Pyaar", "Dil", "Tu"], "medium"],
    ["Complete the actor's name: Ayushmann ___", "Khurrana", ["Kohli", "Kapoor", "Khanna"], "medium"],
    ["Complete the actress's name: Vidya ___", "Balan", ["Bagchi", "Rao", "Sharma"], "medium"],
    ["Complete the director's name: Anurag ___", "Kashyap", ["Basu", "Singh", "Roy"], "medium"],
    ["Complete the film title: Yeh Dillagi... or finish: Dil Dhadakne ___", "Do", ["De", "Lo", "Ja"], "medium"],
    ["Complete the film title: Zindagi Na Milegi ___", "Dobara", ["Kabhi", "Phir Se", "Yun Hi"], "medium"],
    ["Complete the film title: Bhool Bhulaiyaa... finish: Hera ___", "Pheri", ["Pheri 2", "Mantar", "Chakkar"], "medium"],
    ["Complete the actor's name: Nawazuddin ___", "Siddiqui", ["Shah", "Sheikh", "Sayyed"], "hard"],
    ["Complete the actor's name: Pankaj ___", "Tripathi", ["Kapur", "Jha", "Mishra"], "hard"],
    ["Complete the actor's name: Irrfan ___", "Khan", ["Ali", "Sheikh", "Akhtar"], "easy"],
    ["Complete the film title: Gangs of ___", "Wasseypur", ["Mumbai", "Dharavi", "Bihar"], "medium"],
    ["Complete the film title: Andaz Apna ___", "Apna", ["Apnaa", "Sapna", "Yaar"], "medium"],
    ["Complete the dialogue: 'Picture abhi baaki hai mere ___'", "dost", ["yaar", "jaan", "bhai"], "medium"],
    ["Complete the dialogue: 'All is ___'", "well", ["good", "fine", "okay"], "easy"],
    ["Complete the actress's name: Madhuri ___", "Dixit", ["Sharma", "Kapoor", "Sinha"], "easy"],
    ["Complete the director's name: Rohit ___", "Shetty", ["Roy", "Dhawan", "Shukla"], "medium"],
    ["Complete the film title: Bajrangi ___", "Bhaijaan", ["Bhai", "Bossi", "Bhaiya"], "easy"],
  ],
};

(async () => {
  await mongoose.connect(process.env.MONGO_URI);
  let total = 0;
  for (const [category, items] of Object.entries(SETS)) {
    const existing = new Set((await Question.find({ category }, { question: 1 }).lean()).map((d) => d.question));
    const docs = [];
    for (const [q, a, wrong, level] of items) {
      if (existing.has(q)) continue;
      const opts = [a, ...wrong];
      for (let i = opts.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [opts[i], opts[j]] = [opts[j], opts[i]];
      }
      const cfg = LEVEL_CONFIG[level] || LEVEL_CONFIG.easy;
      docs.push({
        category, question: q, options: opts, correctIndex: opts.indexOf(a), correctAnswer: a,
        mediaUrl: "", mediaType: "text", level, xpReward: cfg.xp, timeLimit: cfg.time,
      });
    }
    if (docs.length) await Question.insertMany(docs);
    total += docs.length;
    console.log(`  ${category}: +${docs.length} (now ${await Question.countDocuments({ category })})`);
  }
  console.log(`\nAppended ${total} curated questions.`);
  await mongoose.disconnect();
})().catch((e) => { console.error(e); process.exit(1); });
